In [2]:
import numpy as np
import pandas as pd
from datetime import datetime

In [22]:
#reading in GridLAB-D DPMU data
dpmu_phaseA_aug = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\aug\multi_voltageA.csv')

In [23]:
time = []
time = dpmu_phaseA_aug['# timestamp']

In [24]:
time = pd.Series(time)
time = time.str.split(" ")

In [25]:
for index in range(len(time)):
    del time[index][2]
time

0        [2014-01-01, 00:00:00]
1        [2014-01-01, 00:01:00]
2        [2014-01-01, 00:02:00]
3        [2014-01-01, 00:03:00]
4        [2014-01-01, 00:04:00]
                  ...
44635    [2014-01-31, 23:55:00]
44636    [2014-01-31, 23:56:00]
44637    [2014-01-31, 23:57:00]
44638    [2014-01-31, 23:58:00]
44639    [2014-01-31, 23:59:00]
Name: # timestamp, Length: 44640, dtype: object

In [26]:
month = []
hour = []
for index in range(len(time)):
    month.append(datetime.strptime(time[index][0],'%Y-%m-%d'))
    hour.append(datetime.strptime(time[index][1],'%H:%M:%S'))

In [27]:
date = []
timestamp = []

for index in range(len(time)):
    for jindex in range(len(time[index])):
        if "-" in time[index][jindex]:
            date.append(time[index][jindex].split("-"))
        if ":" in time[index][jindex]:
            timestamp.append(time[index][jindex].split(":"))

In [28]:
date = np.array(date)
date

array([['2014', '01', '01'],
       ['2014', '01', '01'],
       ['2014', '01', '01'],
       ...,
       ['2014', '01', '31'],
       ['2014', '01', '31'],
       ['2014', '01', '31']], dtype='<U4')

In [29]:
timestamp = np.array(timestamp)
timestamp.shape

(44640, 3)

In [30]:
#separating the individual values into different list
year = []
month = []
day = []
for y in range(len(date)):
    year.append(date[y][0])
    month.append(date[y][1])
    day.append(date[y][2])

hour = []
minute = []
sec = []
for y in range(len(timestamp)):
    hour.append(timestamp[y][0])
    minute.append(timestamp[y][1])
    sec.append(timestamp[y][2])

In [31]:
time_df = pd.DataFrame()

In [32]:
time_df["year"] = year
time_df["month"] = month
time_df["day"] = day
time_df["hour"] = hour
time_df["min"] = minute
time_df["sec"] = sec

In [33]:
time_df

       year month day hour min sec
0      2014    01  01   00  00  00
1      2014    01  01   00  01  00
2      2014    01  01   00  02  00
3      2014    01  01   00  03  00
4      2014    01  01   00  04  00
...     ...   ...  ..  ...  ..  ..
44635  2014    01  31   23  55  00
44636  2014    01  31   23  56  00
44637  2014    01  31   23  57  00
44638  2014    01  31   23  58  00
44639  2014    01  31   23  59  00

[44640 rows x 6 columns]

In [34]:
dpmu_phaseA_aug

,# timestamp,Meter2,Meter1,Meter5,Meter3,Meter4,node1_2_3,node4_5_6,node7_8_9,node13_14_15,node10_11_12,node22_23_24,node19_20_21,node16_17_18
0,2014-01-01 00:00:00 EST,+2376.11-37.7522i,+2378.11-36.4051i,+2401.78+0i,+2360.48-65.9106i,+2356.56-67.9253i,+2363.52-47.3755i,+2376.71-36.5935i,+2375.43-37.0229i,+2351.82-66.7492i,+2360.48-65.9106i,+2360.48-66.5672i,+2360.48-65.9084i,+2354.55-68.5855i
1,2014-01-01 00:01:00 EST,+2380.64-35.6745i,+2382.55-34.3321i,+2401.78+0i,+2370.71-60.4802i,+2368.34-61.8416i,+2368.71-45.6639i,+2380.31-34.8428i,+2378.56-35.466i,+2363.63-60.7743i,+2370.71-60.4802i,+2370.59-61.2573i,+2370.71-60.4782i,+2367.82-61.9339i
2,2014-01-01 00:02:00 EST,+2376.95-38.1953i,+2379.12-37.49i,+2401.78+0i,+2365.13-69.4741i,+2361.55-71.615i,+2364.81-48.0594i,+2376.86-38.0843i,+2375.17-38.7911i,+2354.25-70.1793i,+2365.13-69.4741i,+2364.92-70.3296i,+2365.13-69.4721i,+2361.27-71.7088i
3,2014-01-01 00:03:00 EST,+2374.45-39.4867i,+2376.52-38.7381i,+2401.78+0i,+2359.17-72.2675i,+2354.79-74.5122i,+2362.94-49.7032i,+2374.31-39.2843i,+2372.6-39.9372i,+2346.19-72.403i,+2359.17-72.2675i,+2358.97-73.1418i,+2359.17-72.2655i,+2354.61-74.4943i
4,2014-01-01 00:04:00 EST,+2374-37.4056i,+2376.2-36.8712i,+2401.78+0i,+2359.36-68.8561i,+2355.27-71.0111i,+2361.22-46.8924i,+2373.86-37.4375i,+2372.11-38.0634i,+2347.14-69.072i,+2359.36-68.8561i,+2359.23-69.689i,+2359.36-68.854i,+2355.09-70.9983i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44635,2014-01-31 23:55:00 EST,+2376.55-19.575i,+2376.83-19.4679i,+2401.78+0i,+2361.55-28.2131i,+2360.9-27.592i,+2374.61-21.0489i,+2370.63-21.5505i,+2368.82-22.1553i,+2360.37-27.5124i,+2361.55-28.2131i,+2360.84-28.9269i,+2361.54-28.2101i,+2360.39-26.8565i
44636,2014-01-31 23:56:00 EST,+2381.61-12.8831i,+2381.8-12.8103i,+2401.78+0i,+2370.16-14.8104i,+2369.45-13.468i,+2379.94-14.0606i,+2375.95-15.2401i,+2374.31-16.0353i,+2369.06-13.4336i,+2370.16-14.8104i,+2370.37-15.3686i,+2370.16-14.8082i,+2369.07-12.9436i
44637,2014-01-31 23:57:00 EST,+2381.49-13.5617i,+2381.64-13.483i,+2401.78+0i,+2370.53-16.6556i,+2369.89-15.7379i,+2379.95-14.8039i,+2375.5-15.5283i,+2373.81-16.2968i,+2369.5-15.7054i,+2370.53-16.6556i,+2370.89-17.238i,+2370.53-16.6535i,+2369.57-15.6439i
44638,2014-01-31 23:58:00 EST,+2385.62-14.114i,+2385.81-14.1215i,+2401.78+0i,+2375.51-21.0009i,+2374.91-20.2261i,+2383.95-15.2851i,+2381.79-15.7507i,+2381.29-16.0089i,+2374.52-20.2156i,+2375.51-21.0009i,+2375.81-21.6006i,+2375.51-20.9988i,+2374.62-20.2535i
44639,2014-01-31 23:59:00 EST,+2385.92-11.5425i,+2386.29-12.2133i,+2401.78+0i,+2376.39-21.0657i,+2375.74-20.3409i,+2384.39-12.7986i,+2382.82-13.7503i,+2382.53-13.8688i,+2375.36-20.306i,+2376.39-21.0657i,+2376.64-21.6208i,+2376.39-21.0636i,+2375.46-20.3945i

In [35]:
dpmu_phaseA_aug = dpmu_phaseA_aug.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseA_aug

,Meter2,Meter1,Meter3,Meter4,node1_2_3,node4_5_6,node7_8_9,node13_14_15,node10_11_12,node22_23_24,node19_20_21,node16_17_18
0,+2376.11-37.7522i,+2378.11-36.4051i,+2360.48-65.9106i,+2356.56-67.9253i,+2363.52-47.3755i,+2376.71-36.5935i,+2375.43-37.0229i,+2351.82-66.7492i,+2360.48-65.9106i,+2360.48-66.5672i,+2360.48-65.9084i,+2354.55-68.5855i
1,+2380.64-35.6745i,+2382.55-34.3321i,+2370.71-60.4802i,+2368.34-61.8416i,+2368.71-45.6639i,+2380.31-34.8428i,+2378.56-35.466i,+2363.63-60.7743i,+2370.71-60.4802i,+2370.59-61.2573i,+2370.71-60.4782i,+2367.82-61.9339i
2,+2376.95-38.1953i,+2379.12-37.49i,+2365.13-69.4741i,+2361.55-71.615i,+2364.81-48.0594i,+2376.86-38.0843i,+2375.17-38.7911i,+2354.25-70.1793i,+2365.13-69.4741i,+2364.92-70.3296i,+2365.13-69.4721i,+2361.27-71.7088i
3,+2374.45-39.4867i,+2376.52-38.7381i,+2359.17-72.2675i,+2354.79-74.5122i,+2362.94-49.7032i,+2374.31-39.2843i,+2372.6-39.9372i,+2346.19-72.403i,+2359.17-72.2675i,+2358.97-73.1418i,+2359.17-72.2655i,+2354.61-74.4943i
4,+2374-37.4056i,+2376.2-36.8712i,+2359.36-68.8561i,+2355.27-71.0111i,+2361.22-46.8924i,+2373.86-37.4375i,+2372.11-38.0634i,+2347.14-69.072i,+2359.36-68.8561i,+2359.23-69.689i,+2359.36-68.854i,+2355.09-70.9983i
...,...,...,...,...,...,...,...,...,...,...,...,...
44635,+2376.55-19.575i,+2376.83-19.4679i,+2361.55-28.2131i,+2360.9-27.592i,+2374.61-21.0489i,+2370.63-21.5505i,+2368.82-22.1553i,+2360.37-27.5124i,+2361.55-28.2131i,+2360.84-28.9269i,+2361.54-28.2101i,+2360.39-26.8565i
44636,+2381.61-12.8831i,+2381.8-12.8103i,+2370.16-14.8104i,+2369.45-13.468i,+2379.94-14.0606i,+2375.95-15.2401i,+2374.31-16.0353i,+2369.06-13.4336i,+2370.16-14.8104i,+2370.37-15.3686i,+2370.16-14.8082i,+2369.07-12.9436i
44637,+2381.49-13.5617i,+2381.64-13.483i,+2370.53-16.6556i,+2369.89-15.7379i,+2379.95-14.8039i,+2375.5-15.5283i,+2373.81-16.2968i,+2369.5-15.7054i,+2370.53-16.6556i,+2370.89-17.238i,+2370.53-16.6535i,+2369.57-15.6439i
44638,+2385.62-14.114i,+2385.81-14.1215i,+2375.51-21.0009i,+2374.91-20.2261i,+2383.95-15.2851i,+2381.79-15.7507i,+2381.29-16.0089i,+2374.52-20.2156i,+2375.51-21.0009i,+2375.81-21.6006i,+2375.51-20.9988i,+2374.62-20.2535i
44639,+2385.92-11.5425i,+2386.29-12.2133i,+2376.39-21.0657i,+2375.74-20.3409i,+2384.39-12.7986i,+2382.82-13.7503i,+2382.53-13.8688i,+2375.36-20.306i,+2376.39-21.0657i,+2376.64-21.6208i,+2376.39-21.0636i,+2375.46-20.3945i

In [40]:
inverse_inputs = pd.concat([dpmu_phaseA_aug,time_df], axis=1)

In [41]:
inverse_inputs

,Meter2,Meter1,Meter3,Meter4,node1_2_3,node4_5_6,node7_8_9,node13_14_15,node10_11_12,node22_23_24,node19_20_21,node16_17_18,year,month,day,hour,min,sec
0,+2376.11-37.7522i,+2378.11-36.4051i,+2360.48-65.9106i,+2356.56-67.9253i,+2363.52-47.3755i,+2376.71-36.5935i,+2375.43-37.0229i,+2351.82-66.7492i,+2360.48-65.9106i,+2360.48-66.5672i,+2360.48-65.9084i,+2354.55-68.5855i,2014,01,01,00,00,00
1,+2380.64-35.6745i,+2382.55-34.3321i,+2370.71-60.4802i,+2368.34-61.8416i,+2368.71-45.6639i,+2380.31-34.8428i,+2378.56-35.466i,+2363.63-60.7743i,+2370.71-60.4802i,+2370.59-61.2573i,+2370.71-60.4782i,+2367.82-61.9339i,2014,01,01,00,01,00
2,+2376.95-38.1953i,+2379.12-37.49i,+2365.13-69.4741i,+2361.55-71.615i,+2364.81-48.0594i,+2376.86-38.0843i,+2375.17-38.7911i,+2354.25-70.1793i,+2365.13-69.4741i,+2364.92-70.3296i,+2365.13-69.4721i,+2361.27-71.7088i,2014,01,01,00,02,00
3,+2374.45-39.4867i,+2376.52-38.7381i,+2359.17-72.2675i,+2354.79-74.5122i,+2362.94-49.7032i,+2374.31-39.2843i,+2372.6-39.9372i,+2346.19-72.403i,+2359.17-72.2675i,+2358.97-73.1418i,+2359.17-72.2655i,+2354.61-74.4943i,2014,01,01,00,03,00
4,+2374-37.4056i,+2376.2-36.8712i,+2359.36-68.8561i,+2355.27-71.0111i,+2361.22-46.8924i,+2373.86-37.4375i,+2372.11-38.0634i,+2347.14-69.072i,+2359.36-68.8561i,+2359.23-69.689i,+2359.36-68.854i,+2355.09-70.9983i,2014,01,01,00,04,00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44635,+2376.55-19.575i,+2376.83-19.4679i,+2361.55-28.2131i,+2360.9-27.592i,+2374.61-21.0489i,+2370.63-21.5505i,+2368.82-22.1553i,+2360.37-27.5124i,+2361.55-28.2131i,+2360.84-28.9269i,+2361.54-28.2101i,+2360.39-26.8565i,2014,01,31,23,55,00
44636,+2381.61-12.8831i,+2381.8-12.8103i,+2370.16-14.8104i,+2369.45-13.468i,+2379.94-14.0606i,+2375.95-15.2401i,+2374.31-16.0353i,+2369.06-13.4336i,+2370.16-14.8104i,+2370.37-15.3686i,+2370.16-14.8082i,+2369.07-12.9436i,2014,01,31,23,56,00
44637,+2381.49-13.5617i,+2381.64-13.483i,+2370.53-16.6556i,+2369.89-15.7379i,+2379.95-14.8039i,+2375.5-15.5283i,+2373.81-16.2968i,+2369.5-15.7054i,+2370.53-16.6556i,+2370.89-17.238i,+2370.53-16.6535i,+2369.57-15.6439i,2014,01,31,23,57,00
44638,+2385.62-14.114i,+2385.81-14.1215i,+2375.51-21.0009i,+2374.91-20.2261i,+2383.95-15.2851i,+2381.79-15.7507i,+2381.29-16.0089i,+2374.52-20.2156i,+2375.51-21.0009i,+2375.81-21.6006i,+2375.51-20.9988i,+2374.62-20.2535i,2014,01,31,23,58,00
44639,+2385.92-11.5425i,+2386.29-12.2133i,+2376.39-21.0657i,+2375.74-20.3409i,+2384.39-12.7986i,+2382.82-13.7503i,+2382.53-13.8688i,+2375.36-20.306i,+2376.39-21.0657i,+2376.64-21.6208i,+2376.39-21.0636i,+2375.46-20.3945i,2014,01,31,23,59,00