In [2]:
import numpy as np
import pandas as pd
import os

# Data Preprocessing

In [3]:
#reading 3 phase DPMU output from gridlabD
dpmu_phaseA = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\aug\multi_voltageA.csv')
dpmu_phaseB = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\aug\multi_voltageB.csv')
dpmu_phaseC = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\aug\multi_voltageC.csv')

In [4]:
dpmu_phaseA

,# timestamp,Meter2,Meter1,Meter5,Meter3,Meter4,1_2_3,4_5_6,7_8_9,13_14_15,10_11_12,22_23_24,19_20_21,16_17_18
0,2018-08-01 00:00:00 CDT,+2401.78-6.677e-010i,+2401.78-6.67515e-010i,+2401.78+0i,+2401.78-1.3315e-009i,+2401.78-1.33273e-009i,+2401.78-6.677e-010i,+2401.78-6.68147e-010i,+2401.78-6.68147e-010i,+2401.78-1.33273e-009i,+2401.78-1.3315e-009i,+2401.78-1.3316e-009i,+2401.78-1.3316e-009i,+2401.78-1.33273e-009i
1,2018-08-01 00:01:00 CDT,+2401.78-1.53652e-009i,+2401.78-1.53672e-009i,+2401.78+0i,+2401.78-3.0723e-009i,+2401.78-3.07346e-009i,+2401.78-1.53652e-009i,+2401.78-1.53709e-009i,+2401.78-1.53709e-009i,+2401.78-3.07346e-009i,+2401.78-3.0723e-009i,+2401.78-3.07208e-009i,+2401.78-3.07208e-009i,+2401.78-3.07346e-009i
2,2018-08-01 00:02:00 CDT,+2401.78+4.96263e-009i,+2401.78+4.96245e-009i,+2401.78+0i,+2401.78+9.92528e-009i,+2401.78+9.92464e-009i,+2401.78+4.96263e-009i,+2401.78+4.96189e-009i,+2401.78+4.96189e-009i,+2401.78+9.92464e-009i,+2401.78+9.92528e-009i,+2401.78+9.92528e-009i,+2401.78+9.92528e-009i,+2401.78+9.92464e-009i
3,2018-08-01 00:03:00 CDT,+2401.78-2.99842e-010i,+2401.78-3.00259e-010i,+2401.78+0i,+2401.78-6.0017e-010i,+2401.78-6.00645e-010i,+2401.78-2.99842e-010i,+2401.78-3.00993e-010i,+2401.78-3.00993e-010i,+2401.78-6.00645e-010i,+2401.78-6.0017e-010i,+2401.78-5.99992e-010i,+2401.78-5.99992e-010i,+2401.78-6.00645e-010i
4,2018-08-01 00:04:00 CDT,+2401.78+4.62254e-009i,+2401.78+4.6224e-009i,+2401.78+0i,+2401.78+9.24438e-009i,+2401.78+9.2435e-009i,+2401.78+4.62254e-009i,+2401.78+4.62166e-009i,+2401.78+4.62166e-009i,+2401.78+9.2435e-009i,+2401.78+9.24438e-009i,+2401.78+9.24428e-009i,+2401.78+9.24428e-009i,+2401.78+9.2435e-009i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44635,2018-08-31 23:55:00 CDT,+2389.12-25.6399i,+2388.2-25.7631i,+2401.78+0i,+2373.81-48.3224i,+2371.55-50.2265i,+2386.95-27.1563i,+2385.93-26.5561i,+2384.19-27.3061i,+2367.26-49.5283i,+2373.81-48.3224i,+2372.97-49.0974i,+2373.81-48.3195i,+2370.78-50.711i
44636,2018-08-31 23:56:00 CDT,+2379.96-24.6927i,+2379.21-25.2192i,+2401.78+0i,+2363.39-42.3781i,+2361.31-43.3462i,+2377.89-26.2714i,+2372.97-27.3556i,+2371.17-28.0541i,+2357.01-42.3523i,+2363.39-42.3781i,+2362.5-43.1028i,+2363.39-42.375i,+2361.07-43.5705i
44637,2018-08-31 23:57:00 CDT,+2380.08-18.0444i,+2379.32-19.0202i,+2401.78+0i,+2361.72-33.4432i,+2359.84-33.9173i,+2378.17-19.716i,+2374-21.1249i,+2372.6-21.6941i,+2355.56-32.8314i,+2361.72-33.4432i,+2360.82-34.0922i,+2361.71-33.44i,+2359.92-34.0828i
44638,2018-08-31 23:58:00 CDT,+2378.04-19.9124i,+2378.64-19.5764i,+2401.78+0i,+2363.58-35.246i,+2361.73-35.8699i,+2368.4-28.2786i,+2374.27-19.8813i,+2373.68-19.5555i,+2357.41-34.9363i,+2363.58-35.246i,+2362.71-35.8845i,+2363.58-35.243i,+2361.79-36.0449i
44639,2018-08-31 23:59:00 CDT,+2374.58-19.8343i,+2375.59-19.0548i,+2401.78+0i,+2357.51-32.7207i,+2355.45-33.1625i,+2361.97-29.1408i,+2371.69-19.3368i,+2371.37-18.9448i,+2351.27-32.2654i,+2357.51-32.7207i,+2356.68-33.4015i,+2357.51-32.7176i,+2355.52-33.3832i

In [5]:
# dropping meter data
# dpmu_phaseA = dpmu_phaseA.drop(['Meter1', 'Meter2', 'Meter3', 'Meter4', 'Meter5', '# timestamp'], axis=1)
# dpmu_phaseB = dpmu_phaseB.drop(['Meter1', 'Meter2', 'Meter3', 'Meter4', 'Meter5', '# timestamp'], axis=1)
# dpmu_phaseC = dpmu_phaseC.drop(['Meter1', 'Meter2', 'Meter3', 'Meter4', 'Meter5', '# timestamp'], axis=1)

dpmu_phaseA = dpmu_phaseA.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseB = dpmu_phaseB.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseC = dpmu_phaseC.drop(['Meter5', '# timestamp'], axis=1)

In [6]:
phaseA = 0
phaseB = 1
phaseC = 2

In [7]:
# creating target dpmu dataframe
dpmu_data = pd.DataFrame()

In [9]:
for (columnName, columnData) in dpmu_phaseA.iteritems():
    i=0
    if 'Meter' in columnName:
        split = columnName.split('Meter')
        house_name = 'MeterA_'+ split[1]
        i+=1
        dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
        dpmu_data[house_name] = dpmu_values
    else:
        split_column_names = columnName.split('_')
        house_name = 'house'+str(split_column_names[phaseA])
        dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
        dpmu_data[house_name] = dpmu_values

In [10]:
for (columnName, columnData) in dpmu_phaseB.iteritems():
    i=0
    if 'Meter' in columnName:
        split = columnName.split('Meter')
        house_name = 'MeterB_'+ split[1]
        i+=1
        dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
        dpmu_data[house_name] = dpmu_values
    else:
        split_column_names = columnName.split('_')
        house_name = 'house'+str(split_column_names[phaseB])
        dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
        dpmu_data[house_name] = dpmu_values

In [11]:
for (columnName, columnData) in dpmu_phaseC.iteritems():
    i=0
    if 'Meter' in columnName:
        split = columnName.split('Meter')
        house_name = 'MeterC_'+ split[1]
        i+=1
        dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
        dpmu_data[house_name] = dpmu_values
    else:
        split_column_names = columnName.split('_')
        house_name = 'house'+str(split_column_names[phaseC])
        dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
        dpmu_data[house_name] = dpmu_values

In [12]:
dpmu_data

,MeterA_2,MeterA_1,MeterA_3,MeterA_4,house1,house4,house7,house13,house10,house22,...,MeterC_3,MeterC_4,house3,house6,house9,house15,house12,house24,house21,house18
0,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
1,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
2,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
3,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
4,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44635,2389.257579,2388.338958,2374.301786,2372.081808,2387.104473,2386.077784,2384.346363,2367.778064,2374.301786,2373.477865,...,2339.909057,2334.546595,2343.973200,2359.890256,2359.394598,2328.649481,2339.909057,2336.996585,2339.909057,2332.862052
44636,2380.088093,2379.343656,2363.769912,2361.707816,2378.035121,2373.127672,2371.335953,2357.390476,2363.769912,2362.893163,...,2346.367529,2341.574198,2346.678386,2362.453781,2361.973655,2335.601307,2346.367529,2343.556913,2346.367529,2339.980284
44637,2380.148400,2379.396022,2361.956775,2360.083729,2378.251725,2374.093987,2372.699179,2355.788788,2361.956775,2361.066147,...,2355.168952,2350.812653,2354.201535,2368.498071,2368.096015,2344.869655,2355.168952,2352.457341,2355.168952,2349.198187
44638,2378.123366,2378.720556,2363.842782,2362.002380,2368.568817,2374.353238,2373.760552,2357.668860,2363.842782,2362.982489,...,2352.947005,2348.389288,2351.468713,2368.473856,2368.612726,2342.397342,2352.947005,2350.347309,2352.947005,2346.753160
44639,2374.662834,2375.666419,2357.737060,2355.683437,2362.149755,2371.768827,2371.445673,2351.491371,2357.737060,2356.916690,...,2361.530329,2358.183755,2353.803893,2372.652522,2372.809565,2354.149282,2361.530329,2358.928047,2361.535132,2356.402632

In [13]:
# creating input grid dataframe
input_player_df = pd.DataFrame()

In [14]:
directory = r"C:\Users\aniss\grid-edge\data\summer\input_csv\aug"

for filename in os.listdir(directory):
    if str(filename).startswith('25.csv'):
        continue
    player = pd.read_csv(os.path.join(directory, filename))
    player['grid'] = player['grid'].str.replace("i", "j").apply(lambda x: complex(x))
    node_id = player['id'].loc[0]
    column_name_p = 'p_'+str(node_id)
    column_name_q = 'q_'+str(node_id)
#change .head() value to target dataframe row number
    input_player_df[column_name_p] = player['grid'].apply(lambda x: x.real).head(44640)
    input_player_df[column_name_q] = player['grid'].apply(lambda x: x.imag).head(44640)

In [15]:
input_player_df

,p_1,q_1,p_10,q_10,p_11,q_11,p_12,q_12,p_13,q_13,...,p_5,q_5,p_6,q_6,p_7,q_7,p_8,q_8,p_9,q_9
0,43770.0,16469.310048,49815.0,22403.753687,6210.0,2695.012019,7680.0,3179.099513,61020.0,29502.531393,...,53790.0,25326.903353,67515.0,31808.368293,29070.0,10529.067416,6045.0,2515.278484,5310.0,2237.349195
1,43800.0,16489.442538,49830.0,18118.185743,6210.0,2652.451633,7410.0,3283.708947,60975.0,25982.549038,...,53640.0,18459.901687,67395.0,27014.072442,39240.0,14900.141805,6090.0,2647.371431,5295.0,2050.646953
2,43740.0,18093.970905,49980.0,16776.366378,6210.0,2155.374490,7410.0,2942.624906,95295.0,39878.190122,...,53670.0,21365.140495,67035.0,31328.887859,39525.0,16323.012981,6165.0,2984.864340,5265.0,2429.566369
3,43695.0,20767.052779,49920.0,19616.208244,6210.0,2420.677435,7410.0,2509.893336,111255.0,50618.963361,...,53565.0,23865.960887,67005.0,32052.445552,39675.0,13387.876143,8325.0,4010.588460,5280.0,1755.293115
4,43635.0,16530.779025,49875.0,22098.446062,6210.0,2789.715225,8385.0,3529.459545,105225.0,38872.747755,...,53520.0,18590.917043,67050.0,29373.794538,39645.0,15676.843795,7950.0,3506.616212,5265.0,1780.150155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44635,6720.0,2783.210231,52035.0,24418.630981,72225.0,28203.239226,7695.0,3620.339227,6930.0,2692.723848,...,54600.0,19755.024567,70620.0,33218.534846,40200.0,19088.771038,5775.0,2554.586466,7305.0,3011.122825
44636,5550.0,2539.380180,51960.0,24852.282395,72255.0,26619.217900,7920.0,2863.564594,6195.0,2286.259900,...,54690.0,20617.117340,70425.0,29445.121614,40395.0,16284.382985,4815.0,1931.008371,7185.0,3239.030520
44637,5535.0,2377.145083,51870.0,23536.594064,72210.0,28591.535057,7890.0,2850.166224,6210.0,2648.898031,...,54660.0,21157.921748,70515.0,33171.664766,40545.0,17106.067338,4800.0,1607.936207,7140.0,3206.669993
44638,5535.0,2511.753480,51870.0,23979.794916,40785.0,17449.052683,7830.0,3075.092810,6225.0,2808.420788,...,54765.0,21260.283351,70425.0,24380.417452,14040.0,5889.002648,4800.0,1907.035168,7155.0,2937.867317
44639,5550.0,2401.784284,51825.0,19060.016572,25500.0,11404.569433,7935.0,3088.602381,6180.0,2872.144530,...,54555.0,23807.403348,70545.0,23658.398890,8730.0,3479.767501,4800.0,2054.864040,7155.0,2892.343938

# Concat all Summer Data

In [88]:
def DPMU(phase,dpmu_data,phase_letter,letter):
    for (columnName, columnData) in phase.iteritems():
        i=0
        if 'Meter' in columnName:
            split = columnName.split('Meter')
            house_name = f'Meter{letter}_'+ split[1]
            i+=1
            dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
            dpmu_data[house_name] = dpmu_values
        else:
            split_column_names = columnName.split('_')
            house_name = 'house'+str(split_column_names[phase_letter])
            dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
            dpmu_data[house_name] = dpmu_values
    return dpmu_data

In [102]:
def Input(month,input_player_df):
    directory = fr'C:\Users\aniss\grid-edge\data\summer\input_csv\{month}'

    for filename in os.listdir(directory):
        if str(filename).startswith('25.csv'):
            continue
        player = pd.read_csv(os.path.join(directory, filename))
        player['grid'] = player['grid'].str.replace("i", "j").apply(lambda x: complex(x))
        node_id = player['id'].loc[0]
        column_name_p = 'p_'+str(node_id)
        column_name_q = 'q_'+str(node_id)
    #change .head() value to target dataframe row number
        input_player_df[column_name_p] = player['grid'].apply(lambda x: x.real).head(44640)
        input_player_df[column_name_q] = player['grid'].apply(lambda x: x.imag).head(44640)
    return input_player_df

In [45]:
dpmu_phaseA_aug = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\aug\multi_voltageA.csv')
dpmu_phaseB_aug = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\aug\multi_voltageB.csv')
dpmu_phaseC_aug = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\aug\multi_voltageC.csv')

dpmu_phaseA_july = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\july\multi_voltageA.csv')
dpmu_phaseB_july = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\july\multi_voltageB.csv')
dpmu_phaseC_july = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\july\multi_voltageC.csv')

dpmu_phaseA_june = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\june\multi_voltageA.csv')
dpmu_phaseB_june = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\june\multi_voltageB.csv')
dpmu_phaseC_june = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\june\multi_voltageC.csv')

dpmu_phaseA_sept = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\sept\multi_voltageA.csv')
dpmu_phaseB_sept = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\sept\multi_voltageB.csv')
dpmu_phaseC_sept = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\sept\multi_voltageC.csv')

In [46]:
dpmu_phaseA_aug = dpmu_phaseA_aug.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseB_aug = dpmu_phaseB_aug.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseC_aug = dpmu_phaseC_aug.drop(['Meter5', '# timestamp'], axis=1)

dpmu_phaseA_july = dpmu_phaseA_july.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseB_july = dpmu_phaseB_july.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseC_july = dpmu_phaseC_july.drop(['Meter5', '# timestamp'], axis=1)

dpmu_phaseA_june = dpmu_phaseA_june.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseB_june = dpmu_phaseB_june.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseC_june = dpmu_phaseC_june.drop(['Meter5', '# timestamp'], axis=1)

dpmu_phaseA_sept = dpmu_phaseA_sept.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseB_sept = dpmu_phaseB_sept.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseC_sept = dpmu_phaseC_sept.drop(['Meter5', '# timestamp'], axis=1)

In [67]:
phaseA = 0
phaseB = 1
phaseC = 2
A = "A"
B = "B"
C = "C"

In [91]:
dpmu_data_aug = pd.DataFrame()
dpmu_data_july = pd.DataFrame()
dpmu_data_june = pd.DataFrame()
dpmu_data_sept = pd.DataFrame()

In [92]:
dpmu_data_aug = DPMU(dpmu_phaseA_aug,dpmu_data_aug,phaseA, A)
dpmu_data_aug = DPMU(dpmu_phaseB_aug,dpmu_data_aug, phaseB, B)
dpmu_data_aug = DPMU(dpmu_phaseC_aug,dpmu_data_aug, phaseC, C)

dpmu_data_july = DPMU(dpmu_phaseA_aug,dpmu_data_july,phaseA, A)
dpmu_data_july = DPMU(dpmu_phaseB_aug,dpmu_data_july, phaseB, B)
dpmu_data_july = DPMU(dpmu_phaseC_aug,dpmu_data_july, phaseC, C)

dpmu_data_june = DPMU(dpmu_phaseA_aug,dpmu_data_june,phaseA, A)
dpmu_data_june = DPMU(dpmu_phaseB_aug,dpmu_data_june, phaseB, B)
dpmu_data_june = DPMU(dpmu_phaseC_aug,dpmu_data_june, phaseC, C)

dpmu_data_sept = DPMU(dpmu_phaseA_aug,dpmu_data_sept,phaseA, A)
dpmu_data_sept = DPMU(dpmu_phaseB_aug,dpmu_data_sept, phaseB, B)
dpmu_data_sept = DPMU(dpmu_phaseC_aug,dpmu_data_sept, phaseC, C)

In [94]:
dpmu_data = pd.DataFrame()
dpmu_data = pd.concat([dpmu_data_aug, dpmu_data_july,dpmu_data_june,dpmu_data_sept], ignore_index = True)

In [95]:
dpmu_data

,MeterA_2,MeterA_1,MeterA_3,MeterA_4,house1,house4,house7,house13,house10,house22,...,MeterC_3,MeterC_4,house3,house6,house9,house15,house12,house24,house21,house18
0,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
1,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
2,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
3,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
4,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178555,2389.257579,2388.338958,2374.301786,2372.081808,2387.104473,2386.077784,2384.346363,2367.778064,2374.301786,2373.477865,...,2339.909057,2334.546595,2343.973200,2359.890256,2359.394598,2328.649481,2339.909057,2336.996585,2339.909057,2332.862052
178556,2380.088093,2379.343656,2363.769912,2361.707816,2378.035121,2373.127672,2371.335953,2357.390476,2363.769912,2362.893163,...,2346.367529,2341.574198,2346.678386,2362.453781,2361.973655,2335.601307,2346.367529,2343.556913,2346.367529,2339.980284
178557,2380.148400,2379.396022,2361.956775,2360.083729,2378.251725,2374.093987,2372.699179,2355.788788,2361.956775,2361.066147,...,2355.168952,2350.812653,2354.201535,2368.498071,2368.096015,2344.869655,2355.168952,2352.457341,2355.168952,2349.198187
178558,2378.123366,2378.720556,2363.842782,2362.002380,2368.568817,2374.353238,2373.760552,2357.668860,2363.842782,2362.982489,...,2352.947005,2348.389288,2351.468713,2368.473856,2368.612726,2342.397342,2352.947005,2350.347309,2352.947005,2346.753160
178559,2374.662834,2375.666419,2357.737060,2355.683437,2362.149755,2371.768827,2371.445673,2351.491371,2357.737060,2356.916690,...,2361.530329,2358.183755,2353.803893,2372.652522,2372.809565,2354.149282,2361.530329,2358.928047,2361.535132,2356.402632

In [113]:
dpmu_data_2 = dpmu_data[0:175680]

In [103]:
aug = "aug"
july = "july"
june = "june"
sept = "sept"

In [104]:
input_player_df_aug = pd.DataFrame()
input_player_df_july = pd.DataFrame()
input_player_df_june = pd.DataFrame()
input_player_df_sept = pd.DataFrame()

In [106]:
input_player_df_aug = Input(aug,input_player_df_aug)
input_player_df_july = Input(july,input_player_df_july)
input_player_df_june = Input(june,input_player_df_june)
input_player_df_sept = Input(sept,input_player_df_sept)

In [107]:
input_player_df = pd.DataFrame()
input_player_df = pd.concat([input_player_df_aug,input_player_df_july,input_player_df_june,input_player_df_sept], ignore_index=True)

In [108]:
input_player_df

,p_1,q_1,p_10,q_10,p_11,q_11,p_12,q_12,p_13,q_13,...,p_5,q_5,p_6,q_6,p_7,q_7,p_8,q_8,p_9,q_9
0,43770.0,16469.310048,49815.0,22403.753687,6210.0,2695.012019,7680.0,3179.099513,61020.0,29502.531393,...,53790.0,25326.903353,67515.0,31808.368293,29070.0,10529.067416,6045.0,2515.278484,5310.0,2237.349195
1,43800.0,16489.442538,49830.0,18118.185743,6210.0,2652.451633,7410.0,3283.708947,60975.0,25982.549038,...,53640.0,18459.901687,67395.0,27014.072442,39240.0,14900.141805,6090.0,2647.371431,5295.0,2050.646953
2,43740.0,18093.970905,49980.0,16776.366378,6210.0,2155.374490,7410.0,2942.624906,95295.0,39878.190122,...,53670.0,21365.140495,67035.0,31328.887859,39525.0,16323.012981,6165.0,2984.864340,5265.0,2429.566369
3,43695.0,20767.052779,49920.0,19616.208244,6210.0,2420.677435,7410.0,2509.893336,111255.0,50618.963361,...,53565.0,23865.960887,67005.0,32052.445552,39675.0,13387.876143,8325.0,4010.588460,5280.0,1755.293115
4,43635.0,16530.779025,49875.0,22098.446062,6210.0,2789.715225,8385.0,3529.459545,105225.0,38872.747755,...,53520.0,18590.917043,67050.0,29373.794538,39645.0,15676.843795,7950.0,3506.616212,5265.0,1780.150155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175675,6465.0,2972.631054,45765.0,18601.907100,50505.0,22584.311886,8430.0,3328.588776,57450.0,19299.682650,...,4650.0,2208.508764,64635.0,27202.534073,4740.0,1914.997235,41190.0,14957.027472,6705.0,2756.050831
175676,7725.0,2803.379395,45735.0,18923.346659,24030.0,11340.509535,23640.0,8755.127495,57855.0,26046.266930,...,4635.0,1960.976683,62775.0,30129.325651,4725.0,2195.820777,39915.0,16715.076021,6645.0,2334.949333
175677,7650.0,3236.531135,45810.0,21489.054438,18000.0,7522.310477,38730.0,18340.170000,59265.0,22983.504280,...,4635.0,1702.780467,62595.0,26224.452040,3105.0,1118.742920,39375.0,18243.365479,6645.0,2331.013497
175678,7635.0,3083.770012,46065.0,21513.366251,8415.0,3805.158132,39315.0,17865.066637,58860.0,26649.707408,...,4620.0,1994.933092,61470.0,26974.300793,2745.0,1055.999958,39315.0,14768.401004,6645.0,3114.604813
175679,7605.0,3020.594584,46575.0,19290.612690,8445.0,3474.045117,39855.0,13545.269484,57000.0,22595.054086,...,4620.0,2002.153931,60735.0,22461.170215,2745.0,1022.199878,22200.0,8835.499844,6630.0,2507.588774

# Linear Model Training

In [109]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedKFold
from sklearn.linear_model import LinearRegression, Ridge, Lasso, LogisticRegression, SGDRegressor, ElasticNet, RidgeCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import MinMaxScaler
import xgboost as xgb
from pylab import *

In [114]:
# splitting data into train and test datasets
X = input_player_df.copy()
y = dpmu_data_2.copy()

scaler_x = MinMaxScaler()
scaler_x.fit(X)
normalized_x = scaler_x.transform(X)
scaler_y = MinMaxScaler()
scaler_y.fit(y)
normalized_y = scaler_y.transform(y)
    
X_train, X_test, y_train, y_test = train_test_split(normalized_x, normalized_y, test_size=0.33, random_state=42)

In [32]:
y_test.shape

(14732, 36)

## Ordinary Least Squares

In [115]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("MSE: ", (mean_squared_error(y_test, y_pred)))

MSE:  0.012124357406555458

In [36]:
y_test

array([[0.43024622, 0.42986057, 0.44234119, ..., 0.45515354, 0.45854115,
        0.46895496],
       [0.69990555, 0.71149465, 0.73133722, ..., 0.55384852, 0.54961779,
        0.55760762],
       [0.82572067, 0.81447713, 0.84282362, ..., 0.45870779, 0.46482167,
        0.46502154],
       ...,
       [0.5397708 , 0.53871576, 0.55593516, ..., 0.52208204, 0.51849853,
        0.52254762],
       [0.67406778, 0.65523436, 0.64788456, ..., 0.73079766, 0.7247211 ,
        0.7325962 ],
       [0.39451788, 0.38331792, 0.36218836, ..., 0.58653476, 0.58105477,
        0.59045469]])

In [39]:
y_pred

array([[0.46029834, 0.45509918, 0.44810196, ..., 0.49324218, 0.48917813,
        0.49612703],
       [0.59275047, 0.59725945, 0.61237036, ..., 0.62708905, 0.6269492 ,
        0.63609951],
       [0.76315693, 0.75296435, 0.76081399, ..., 0.6191779 , 0.6231838 ,
        0.63001511],
       ...,
       [0.59252091, 0.59247304, 0.58884076, ..., 0.54180885, 0.54037541,
        0.55271366],
       [0.64564669, 0.63943248, 0.64425246, ..., 0.72264428, 0.72011022,
        0.7210659 ],
       [0.57946729, 0.57699505, 0.57853069, ..., 0.51783075, 0.5222306 ,
        0.53818593]])

In [ ]:
# normalise data
# use rmse and scale it to the original signal -> what is the magnitude of the signal we are trying to predict
# every sample is 24x1 -> what is the average norm of that vector? -> how to evaluate error of model
# mse grows linearly with inputs

In [23]:
y_pred.shape

(14732, 36)

## Lasso Model

In [37]:
model = Lasso()

model.fit(X_train, y_train)
        
y_pred = model.predict(X_test)
print(mean_squared_error(y_test, y_pred))

0.0171241204202973

## Ridge Model

In [116]:
model = Ridge()
model.fit(X_train, y_train)
        
y_pred = model.predict(X_test)
print(mean_squared_error(y_test, y_pred))

0.012124322218466712

In [40]:
model = RidgeCV(alphas=[1e-3, 1e-2, 1e-1, 1]).fit(X_train, y_train)
y_pred = model.predict(X_test)
print(mean_squared_error(y_test, y_pred))

0.010152678682675316

## Elastic Net with Cross Validation and Hyperparameter Tuning

In [44]:
model = ElasticNet()

# define model evaluation method
cv = RepeatedKFold(n_splits=3, n_repeats=3, random_state=1)
# define grid
grid = dict()
grid['alpha'] = [1e-2, 1e-1, 1]
grid['l1_ratio'] = arange(0, 1, 0.1)
# define search
search = GridSearchCV(model, grid, scoring='neg_mean_squared_error', cv=cv, n_jobs=-1)
# perform the search
results = search.fit(X_train, y_train)
# summarize
print('MSE: %.3f' % results.best_score_)
print('Config: %s' % results.best_params_)

In [42]:
model = ElasticNet()

In [43]:
model = ElasticNet(alpha=100, l1_ratio=0.0)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("MSE: ", mean_squared_error(y_test, y_pred))

C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 251.82952949721698, tolerance: 0.05041201135548906
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 246.45765555344084, tolerance: 0.04933683279040945
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 266.86680688287987, tolerance: 0.05342448643325658
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 255.57731710229797, tolerance: 0.051164853920694586
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 348.5959557285708, tolerance: 0.06979173770822632
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 251.0560505360056, tolerance: 0.0502599162083866
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 251.60659589026267, tolerance: 0.05037057339905545
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 248.30063259023427, tolerance: 0.04970889855968858
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 270.4935736594981, tolerance: 0.05415140883875635
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 266.8758603374802, tolerance: 0.05342630008065377
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 254.45702890868998, tolerance: 0.05094110248401249
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 182.76993012905896, tolerance: 0.03655885062325224
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 187.17987960622705, tolerance: 0.03744111692567943
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 185.23384587116507, tolerance: 0.037052336741708394
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 192.70929807944606, tolerance: 0.03854748829687261
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 224.35681865664824, tolerance: 0.04488455760615869
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 195.82961801026588, tolerance: 0.03917118880269752
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 196.05005779251647, tolerance: 0.03921527078452287
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 197.3505576454725, tolerance: 0.039475200544262866
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 184.39832506809392, tolerance: 0.03688512258285307
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 185.23635285998307, tolerance: 0.037052838089658535
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 202.16938033884495, tolerance: 0.04044029109111813
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 338.80152701641066, tolerance: 0.06785352736892307
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 341.6831657463027, tolerance: 0.06842842822025764
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 287.42338911586666, tolerance: 0.05755048742892406
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 281.80942741955545, tolerance: 0.056426093934310875
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 320.4964823607384, tolerance: 0.06418996881972729
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 340.9315885022142, tolerance: 0.0682855439640901
  model = cd_fast.enet_coordinate_descent(

C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 333.39574314100304, tolerance: 0.0667765930407424
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 288.65864528996906, tolerance: 0.05779873249115196
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 292.56381116999387, tolerance: 0.05857850176737018
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 287.43252122054, tolerance: 0.057552316238576304
  model = cd_fast.enet_coordinate_descent(

MSE:  0.017094343589100527

C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 275.8723096034738, tolerance: 0.0552368007903797
  model = cd_fast.enet_coordinate_descent(

# Neural Network

In [ ]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_regression
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# get the dataset
def get_dataset():
    X, y = input_player_df.copy().to_numpy(), dpmu_data.copy().to_numpy()
    return X, y

In [ ]:
# get the model
def get_model(n_inputs, n_outputs):
    model = Sequential()
    model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
    model.add(Dense(n_outputs))
    model.compile(loss='mse', optimizer='adam')
    return model

In [ ]:
# evaluate a model using repeated k-fold cross-validation
def evaluate_model(X, y):
    results = list()
    n_inputs, n_outputs = X.shape[1], y.shape[1]
    # define evaluation procedure
    cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
    # enumerate folds
    for train_ix, test_ix in cv.split(X):
        # prepare data
        X_train, X_test = X[train_ix], X[test_ix]
        y_train, y_test = y[train_ix], y[test_ix]
        # define model
        model = get_model(n_inputs, n_outputs)
        # fit model
        model.fit(X_train, y_train, verbose=0, epochs=100)
        # evaluate model on test set
        mse = model.evaluate(X_test, y_test, verbose=0)
        # store result
        print(mse)
        results.append(mse)
        return results

In [ ]:
# load dataset
X, y = get_dataset()
# evaluate model
results = evaluate_model(X, y)
# summarize performance
print('MSE: %.3f (%.3f)' % (mean(results), std(results)))