In [1]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive/Shareddrives/Senior_Design/PecanStreet')

In [ ]:
#reading in grid values from pecan street dataport

#df = pd.read_csv('shared/Dataport-Data/electricity_data/Austin/1minute_data_austin.csv.gz', compression='gzip')
df = pd.read_csv('1minute_data_austin.csv.gz', compression='gzip')

MemoryError: Unable to allocate 64.0 KiB for an array with shape (8192,) and data type int64

In [ ]:
df

,dataid,localminute,air1,air2,air3,airwindowunit1,aquarium1,bathroom1,bathroom2,bedroom1,...,sprinkler1,sumppump1,utilityroom1,venthood1,waterheater1,waterheater2,wellpump1,winecooler1,leg1v,leg2v
0,661,2018-01-01 01:21:00-06,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,661,2018-01-01 01:00:00-06,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,661,2018-01-01 01:01:00-06,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,661,2018-01-01 01:02:00-06,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,661,2018-01-01 01:03:00-06,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13100534,7951,2018-02-07 15:26:00-06,0.0,0.007,NaN,NaN,NaN,-0.003,0.003,NaN,...,NaN,NaN,NaN,NaN,-0.001,NaN,NaN,NaN,122.726,122.830
13100535,7951,2018-02-07 15:27:00-06,0.0,0.008,NaN,NaN,NaN,-0.003,0.003,NaN,...,NaN,NaN,NaN,NaN,-0.001,NaN,NaN,NaN,122.800,122.738
13100536,7951,2018-02-07 15:28:00-06,0.0,0.005,NaN,NaN,NaN,-0.002,0.003,NaN,...,NaN,NaN,NaN,NaN,-0.001,NaN,NaN,NaN,122.945,122.728
13100537,7951,2018-02-07 15:29:00-06,0.0,0.004,NaN,NaN,NaN,-0.002,0.003,NaN,...,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN,122.907,122.724
13100538,7951,2018-02-07 15:30:00-06,0.0,0.002,NaN,NaN,NaN,-0.001,0.003,NaN,...,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN,122.914,122.858

In [ ]:
#reading DPMU phase A output from gridlabD
dpmu_phaseA = pd.read_csv('multi_voltageA.csv')
dpmu_phaseB = pd.read_csv('multi_voltageB.csv')
dpmu_phaseC = pd.read_csv('multi_voltageC.csv')

In [ ]:
#within the GridLabD output (DPMU), isolate Node661 
node_661_dpmu_phaseA = pd.DataFrame(dpmu_phaseA, columns=['# timestamp', 'Node661'])
node_661_dpmu_phaseB = pd.DataFrame(dpmu_phaseB, columns=['# timestamp', 'Node661'])
node_661_dpmu_phaseC = pd.DataFrame(dpmu_phaseC, columns=['# timestamp', 'Node661'])

In [ ]:
node_661_dpmu_phaseA

                  # timestamp             Node661
0     2018-01-01 00:00:00 CST  +2404.44-0.558893i
1     2018-01-01 00:01:00 CST   +2404.41-0.56357i
2     2018-01-01 00:02:00 CST  +2404.44-0.601357i
3     2018-01-01 00:03:00 CST  +2404.94-0.697312i
4     2018-01-01 00:04:00 CST     +2406.7-1.0308i
...                       ...                 ...
1436  2018-01-01 23:56:00 CST  +2402.51-0.972891i
1437  2018-01-01 23:57:00 CST  +2402.65-0.981452i
1438  2018-01-01 23:58:00 CST  +2402.56-0.931149i
1439  2018-01-01 23:59:00 CST   +2403.01-0.84144i
1440  2018-01-02 00:00:00 CST  +2403.25-0.685989i

[1441 rows x 2 columns]

In [ ]:
node_661_dpmu_phaseB

                  # timestamp            Node661
0     2018-01-01 00:00:00 CST  -1198.52-2080.58j
1     2018-01-01 00:01:00 CST  -1198.54-2080.58j
2     2018-01-01 00:02:00 CST  -1198.52-2080.61j
3     2018-01-01 00:03:00 CST  -1198.06-2080.71j
4     2018-01-01 00:04:00 CST  -1196.45-2081.05j
...                       ...                ...
1436  2018-01-01 23:56:00 CST  -1200.25-2080.89j
1437  2018-01-01 23:57:00 CST   -1200.13-2080.9j
1438  2018-01-01 23:58:00 CST   -1200.2-2080.86j
1439  2018-01-01 23:59:00 CST    -1199.8-2080.8j
1440  2018-01-02 00:00:00 CST  -1199.58-2080.66j

[1441 rows x 2 columns]

In [ ]:
node_661_dpmu_phaseC

                  # timestamp            Node661
0     2018-01-01 00:00:00 CST   -1194.39+2078.2j
1     2018-01-01 00:01:00 CST  -1194.44+2078.18j
2     2018-01-01 00:02:00 CST  -1194.38+2078.09j
3     2018-01-01 00:03:00 CST   -1193.16+2077.9j
4     2018-01-01 00:04:00 CST  -1188.88+2077.28j
...                       ...                ...
1436  2018-01-01 23:56:00 CST  -1199.27+2077.57j
1437  2018-01-01 23:57:00 CST   -1198.9+2077.41j
1438  2018-01-01 23:58:00 CST  -1199.08+2077.67j
1439  2018-01-01 23:59:00 CST  -1197.88+2077.77j
1440  2018-01-02 00:00:00 CST   -1197.26+2078.1j

[1441 rows x 2 columns]

In [ ]:
# converting dpmu string values to complex dtype
node_661_dpmu_phaseA['Node661'] = node_661_dpmu_phaseA['Node661'].str.replace("i", "j").apply(lambda x: complex(x))
node_661_dpmu_phaseB['Node661'] = node_661_dpmu_phaseB['Node661'].str.replace("i", "j").apply(lambda x: complex(x))
node_661_dpmu_phaseC['Node661'] = node_661_dpmu_phaseC['Node661'].str.replace("i", "j").apply(lambda x: complex(x))

In [ ]:
# splitting dpmu phase A values into real and imaginary parts
node_661_dpmu_phaseA['timestamp'] = node_661_dpmu_phaseA['# timestamp'].str.replace('CST', '')
node_661_dpmu_phaseA['realA'] = node_661_dpmu_phaseA['Node661'].apply(lambda x : x.real)
node_661_dpmu_phaseA['imagA'] = node_661_dpmu_phaseA['Node661'].apply(lambda x : x.imag)
node_661_dpmu_phaseA = pd.DataFrame(node_661_dpmu_phaseA, columns = ['timestamp', 'realA', 'imagA'])
node_661_dpmu_phaseA

                 timestamp    realA     imagA
0     2018-01-01 00:00:00   2404.44 -0.558893
1     2018-01-01 00:01:00   2404.41 -0.563570
2     2018-01-01 00:02:00   2404.44 -0.601357
3     2018-01-01 00:03:00   2404.94 -0.697312
4     2018-01-01 00:04:00   2406.70 -1.030800
...                    ...      ...       ...
1436  2018-01-01 23:56:00   2402.51 -0.972891
1437  2018-01-01 23:57:00   2402.65 -0.981452
1438  2018-01-01 23:58:00   2402.56 -0.931149
1439  2018-01-01 23:59:00   2403.01 -0.841440
1440  2018-01-02 00:00:00   2403.25 -0.685989

[1441 rows x 3 columns]

In [ ]:
# splitting dpmu phase B values into real and imaginary parts
node_661_dpmu_phaseB['timestamp'] = node_661_dpmu_phaseB['# timestamp'].str.replace('CST', '')
node_661_dpmu_phaseB['realB'] = node_661_dpmu_phaseB['Node661'].apply(lambda x : x.real)
node_661_dpmu_phaseB['imagB'] = node_661_dpmu_phaseB['Node661'].apply(lambda x : x.imag)
node_661_dpmu_phaseB = pd.DataFrame(node_661_dpmu_phaseB, columns = ['timestamp', 'realB', 'imagB'])
node_661_dpmu_phaseB

                 timestamp    realB    imagB
0     2018-01-01 00:00:00  -1198.52 -2080.58
1     2018-01-01 00:01:00  -1198.54 -2080.58
2     2018-01-01 00:02:00  -1198.52 -2080.61
3     2018-01-01 00:03:00  -1198.06 -2080.71
4     2018-01-01 00:04:00  -1196.45 -2081.05
...                    ...      ...      ...
1436  2018-01-01 23:56:00  -1200.25 -2080.89
1437  2018-01-01 23:57:00  -1200.13 -2080.90
1438  2018-01-01 23:58:00  -1200.20 -2080.86
1439  2018-01-01 23:59:00  -1199.80 -2080.80
1440  2018-01-02 00:00:00  -1199.58 -2080.66

[1441 rows x 3 columns]

In [ ]:
# splitting dpmu phase C values into real and imaginary parts
node_661_dpmu_phaseC['timestamp'] = node_661_dpmu_phaseC['# timestamp'].str.replace('CST', '')
node_661_dpmu_phaseC['realC'] = node_661_dpmu_phaseC['Node661'].apply(lambda x : x.real)
node_661_dpmu_phaseC['imagC'] = node_661_dpmu_phaseC['Node661'].apply(lambda x : x.imag)
node_661_dpmu_phaseC = pd.DataFrame(node_661_dpmu_phaseC, columns = ['timestamp', 'realC', 'imagC'])
node_661_dpmu_phaseC

                 timestamp    realC    imagC
0     2018-01-01 00:00:00  -1194.39  2078.20
1     2018-01-01 00:01:00  -1194.44  2078.18
2     2018-01-01 00:02:00  -1194.38  2078.09
3     2018-01-01 00:03:00  -1193.16  2077.90
4     2018-01-01 00:04:00  -1188.88  2077.28
...                    ...      ...      ...
1436  2018-01-01 23:56:00  -1199.27  2077.57
1437  2018-01-01 23:57:00  -1198.90  2077.41
1438  2018-01-01 23:58:00  -1199.08  2077.67
1439  2018-01-01 23:59:00  -1197.88  2077.77
1440  2018-01-02 00:00:00  -1197.26  2078.10

[1441 rows x 3 columns]

In [ ]:
#within the PecanStreet data, get all grid values for Node661
node_661_grid = df.loc[df['dataid'] == 661]
#node_661_grid = pd.DataFrame(node661_grid, columns = ['localminute', 'grid'])
node_661_grid['timestamp'] = node_661_grid['localminute'].str.replace('-06', '')
node_661_grid = pd.DataFrame(node_661_grid, columns = ['timestamp', 'grid'])
node_661_grid

NameError: name 'df' is not defined

In [ ]:
node_661_player = pd.read_csv('661.csv')
node_661_player.columns

Index(['grid', 'id'], dtype='object')

In [ ]:
#node_661_player['timestamp'] = node_661_player[node_661_player.columns[0]]
node_661_player['complex_player'] = node_661_player['grid']
node_661_player = node_661_player.drop(axis=1, columns=['grid', 'id'])
#node_661_player = pd.DataFrame(node_661_player, columns = ['timestamp', 'complex_player'])
node_661_player

            complex_player
0       1806.0+829.690301j
1       1817.0+662.706179j
2        1804.0+640.78435j
3       1761.0+761.855487j
4        1672.0+750.42114j
...                    ...
517075  -669.0+261.743076j
517076  -683.0+250.279162j
517077  -576.0+215.620848j
517078  -590.0+199.545519j
517079  -541.0+214.387475j

[517080 rows x 1 columns]

In [ ]:
node_661_player['complex_player'] = node_661_player['complex_player'].str.replace("i", "j").apply(lambda x: complex(x))
node_661_player['real'] = node_661_player['complex_player'].apply(lambda x : x.real)
node_661_player['imag'] = node_661_player['complex_player'].apply(lambda x : x.imag)
node_661_player = pd.DataFrame(node_661_player, columns = [node_661_player.columns[0], 'real', 'imag']).head(1441).drop(axis=1, columns=['complex_player'])
node_661_player

        real        imag
0     1806.0  829.690301
1     1817.0  662.706179
2     1804.0  640.784350
3     1761.0  761.855487
4     1672.0  750.421140
...      ...         ...
1436   766.0  360.497549
1437   766.0  259.525374
1438   652.0  302.948004
1439   383.0  182.293501
1440   383.0  134.214955

[1441 rows x 2 columns]

In [ ]:
all_phases_dpmu = pd.DataFrame({'realA': node_661_dpmu_phaseA['realA'], 'imagA': node_661_dpmu_phaseA['imagA'], 'realB': node_661_dpmu_phaseB['realB'], 'imagB': node_661_dpmu_phaseB['imagB'], 'realC': node_661_dpmu_phaseC['realC'], 'imagC': node_661_dpmu_phaseC['imagC'] }).head(524709)
all_phases_dpmu

        realA     imagA    realB    imagB    realC    imagC
0     2404.44 -0.558893 -1198.52 -2080.58 -1194.39  2078.20
1     2404.41 -0.563570 -1198.54 -2080.58 -1194.44  2078.18
2     2404.44 -0.601357 -1198.52 -2080.61 -1194.38  2078.09
3     2404.94 -0.697312 -1198.06 -2080.71 -1193.16  2077.90
4     2406.70 -1.030800 -1196.45 -2081.05 -1188.88  2077.28
...       ...       ...      ...      ...      ...      ...
1436  2402.51 -0.972891 -1200.25 -2080.89 -1199.27  2077.57
1437  2402.65 -0.981452 -1200.13 -2080.90 -1198.90  2077.41
1438  2402.56 -0.931149 -1200.20 -2080.86 -1199.08  2077.67
1439  2403.01 -0.841440 -1199.80 -2080.80 -1197.88  2077.77
1440  2403.25 -0.685989 -1199.58 -2080.66 -1197.26  2078.10

[1441 rows x 6 columns]

In [ ]:
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression, Ridge, Lasso, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# create datasets
X = pd.DataFrame(node_661_player, columns=['real', 'imag'])
y = all_phases_dpmu

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
print(X.shape)
print(y.shape)

(1441, 2)
(1441, 6)

In [ ]:
# define model
model = LinearRegression()
#model = Ridge(alpha=0.3)
#model = Lasso(alpha=0.5)
# fit model
model.fit(X_train, y_train)
# make a prediction
y_pred = model.predict(X_test)

print(y_pred)
# summarize prediction
print(mean_absolute_error(y_test, y_pred) * 100)

[[ 2.40365986e+03 -7.73114363e-01 -1.19921091e+03 -2.08074535e+03
  -1.19634286e+03  2.07789793e+03]
 [ 2.40014314e+03 -2.14678171e+00 -1.20238454e+03 -2.08185461e+03
  -1.20559941e+03  2.07537332e+03]
 [ 2.40326633e+03 -7.86493426e-01 -1.19956118e+03 -2.08074517e+03
  -1.19733443e+03  2.07797385e+03]
 ...
 [ 2.40179091e+03 -1.30954697e+00 -1.20089081e+03 -2.08116337e+03
  -1.20120116e+03  2.07705070e+03]
 [ 2.40409616e+03 -7.80960950e-01 -1.19882337e+03 -2.08076564e+03
  -1.19525069e+03  2.07775583e+03]
 [ 2.40408784e+03 -8.07086356e-01 -1.19883167e+03 -2.08078853e+03
  -1.19527982e+03  2.07769143e+03]]
92.23040075138128