In [1]:
import numpy as np
from numpy import linalg as LA
import pandas as pd
import os

# Data Preprocessing

In [2]:
#reading 3 phase DPMU output from gridlabD
dpmu_phaseA = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\aug\multi_voltageA.csv')
dpmu_phaseB = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\aug\multi_voltageB.csv')
dpmu_phaseC = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\aug\multi_voltageC.csv')

In [3]:
dpmu_phaseA

,# timestamp,Meter2,Meter1,Meter5,Meter3,Meter4,1_2_3,4_5_6,7_8_9,13_14_15,10_11_12,22_23_24,19_20_21,16_17_18
0,2018-08-01 00:00:00 CDT,+2401.78-6.677e-010i,+2401.78-6.67515e-010i,+2401.78+0i,+2401.78-1.3315e-009i,+2401.78-1.33273e-009i,+2401.78-6.677e-010i,+2401.78-6.68147e-010i,+2401.78-6.68147e-010i,+2401.78-1.33273e-009i,+2401.78-1.3315e-009i,+2401.78-1.3316e-009i,+2401.78-1.3316e-009i,+2401.78-1.33273e-009i
1,2018-08-01 00:01:00 CDT,+2401.78-1.53652e-009i,+2401.78-1.53672e-009i,+2401.78+0i,+2401.78-3.0723e-009i,+2401.78-3.07346e-009i,+2401.78-1.53652e-009i,+2401.78-1.53709e-009i,+2401.78-1.53709e-009i,+2401.78-3.07346e-009i,+2401.78-3.0723e-009i,+2401.78-3.07208e-009i,+2401.78-3.07208e-009i,+2401.78-3.07346e-009i
2,2018-08-01 00:02:00 CDT,+2401.78+4.96263e-009i,+2401.78+4.96245e-009i,+2401.78+0i,+2401.78+9.92528e-009i,+2401.78+9.92464e-009i,+2401.78+4.96263e-009i,+2401.78+4.96189e-009i,+2401.78+4.96189e-009i,+2401.78+9.92464e-009i,+2401.78+9.92528e-009i,+2401.78+9.92528e-009i,+2401.78+9.92528e-009i,+2401.78+9.92464e-009i
3,2018-08-01 00:03:00 CDT,+2401.78-2.99842e-010i,+2401.78-3.00259e-010i,+2401.78+0i,+2401.78-6.0017e-010i,+2401.78-6.00645e-010i,+2401.78-2.99842e-010i,+2401.78-3.00993e-010i,+2401.78-3.00993e-010i,+2401.78-6.00645e-010i,+2401.78-6.0017e-010i,+2401.78-5.99992e-010i,+2401.78-5.99992e-010i,+2401.78-6.00645e-010i
4,2018-08-01 00:04:00 CDT,+2401.78+4.62254e-009i,+2401.78+4.6224e-009i,+2401.78+0i,+2401.78+9.24438e-009i,+2401.78+9.2435e-009i,+2401.78+4.62254e-009i,+2401.78+4.62166e-009i,+2401.78+4.62166e-009i,+2401.78+9.2435e-009i,+2401.78+9.24438e-009i,+2401.78+9.24428e-009i,+2401.78+9.24428e-009i,+2401.78+9.2435e-009i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44635,2018-08-31 23:55:00 CDT,+2389.12-25.6399i,+2388.2-25.7631i,+2401.78+0i,+2373.81-48.3224i,+2371.55-50.2265i,+2386.95-27.1563i,+2385.93-26.5561i,+2384.19-27.3061i,+2367.26-49.5283i,+2373.81-48.3224i,+2372.97-49.0974i,+2373.81-48.3195i,+2370.78-50.711i
44636,2018-08-31 23:56:00 CDT,+2379.96-24.6927i,+2379.21-25.2192i,+2401.78+0i,+2363.39-42.3781i,+2361.31-43.3462i,+2377.89-26.2714i,+2372.97-27.3556i,+2371.17-28.0541i,+2357.01-42.3523i,+2363.39-42.3781i,+2362.5-43.1028i,+2363.39-42.375i,+2361.07-43.5705i
44637,2018-08-31 23:57:00 CDT,+2380.08-18.0444i,+2379.32-19.0202i,+2401.78+0i,+2361.72-33.4432i,+2359.84-33.9173i,+2378.17-19.716i,+2374-21.1249i,+2372.6-21.6941i,+2355.56-32.8314i,+2361.72-33.4432i,+2360.82-34.0922i,+2361.71-33.44i,+2359.92-34.0828i
44638,2018-08-31 23:58:00 CDT,+2378.04-19.9124i,+2378.64-19.5764i,+2401.78+0i,+2363.58-35.246i,+2361.73-35.8699i,+2368.4-28.2786i,+2374.27-19.8813i,+2373.68-19.5555i,+2357.41-34.9363i,+2363.58-35.246i,+2362.71-35.8845i,+2363.58-35.243i,+2361.79-36.0449i
44639,2018-08-31 23:59:00 CDT,+2374.58-19.8343i,+2375.59-19.0548i,+2401.78+0i,+2357.51-32.7207i,+2355.45-33.1625i,+2361.97-29.1408i,+2371.69-19.3368i,+2371.37-18.9448i,+2351.27-32.2654i,+2357.51-32.7207i,+2356.68-33.4015i,+2357.51-32.7176i,+2355.52-33.3832i

In [5]:
# dropping meter data
# dpmu_phaseA = dpmu_phaseA.drop(['Meter1', 'Meter2', 'Meter3', 'Meter4', 'Meter5', '# timestamp'], axis=1)
# dpmu_phaseB = dpmu_phaseB.drop(['Meter1', 'Meter2', 'Meter3', 'Meter4', 'Meter5', '# timestamp'], axis=1)
# dpmu_phaseC = dpmu_phaseC.drop(['Meter1', 'Meter2', 'Meter3', 'Meter4', 'Meter5', '# timestamp'], axis=1)

dpmu_phaseA = dpmu_phaseA.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseB = dpmu_phaseB.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseC = dpmu_phaseC.drop(['Meter5', '# timestamp'], axis=1)

In [6]:
phaseA = 0
phaseB = 1
phaseC = 2

In [7]:
# creating target dpmu dataframe
dpmu_data = pd.DataFrame()

In [9]:
for (columnName, columnData) in dpmu_phaseA.iteritems():
    i=0
    if 'Meter' in columnName:
        split = columnName.split('Meter')
        house_name = 'MeterA_'+ split[1]
        i+=1
        dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
        dpmu_data[house_name] = dpmu_values
    else:
        split_column_names = columnName.split('_')
        house_name = 'house'+str(split_column_names[phaseA])
        dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
        dpmu_data[house_name] = dpmu_values

In [10]:
for (columnName, columnData) in dpmu_phaseB.iteritems():
    i=0
    if 'Meter' in columnName:
        split = columnName.split('Meter')
        house_name = 'MeterB_'+ split[1]
        i+=1
        dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
        dpmu_data[house_name] = dpmu_values
    else:
        split_column_names = columnName.split('_')
        house_name = 'house'+str(split_column_names[phaseB])
        dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
        dpmu_data[house_name] = dpmu_values

In [11]:
for (columnName, columnData) in dpmu_phaseC.iteritems():
    i=0
    if 'Meter' in columnName:
        split = columnName.split('Meter')
        house_name = 'MeterC_'+ split[1]
        i+=1
        dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
        dpmu_data[house_name] = dpmu_values
    else:
        split_column_names = columnName.split('_')
        house_name = 'house'+str(split_column_names[phaseC])
        dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
        dpmu_data[house_name] = dpmu_values

In [12]:
dpmu_data

,MeterA_2,MeterA_1,MeterA_3,MeterA_4,house1,house4,house7,house13,house10,house22,...,MeterC_3,MeterC_4,house3,house6,house9,house15,house12,house24,house21,house18
0,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
1,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
2,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
3,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
4,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,2401.780000,...,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840,2401.777840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44635,2389.257579,2388.338958,2374.301786,2372.081808,2387.104473,2386.077784,2384.346363,2367.778064,2374.301786,2373.477865,...,2339.909057,2334.546595,2343.973200,2359.890256,2359.394598,2328.649481,2339.909057,2336.996585,2339.909057,2332.862052
44636,2380.088093,2379.343656,2363.769912,2361.707816,2378.035121,2373.127672,2371.335953,2357.390476,2363.769912,2362.893163,...,2346.367529,2341.574198,2346.678386,2362.453781,2361.973655,2335.601307,2346.367529,2343.556913,2346.367529,2339.980284
44637,2380.148400,2379.396022,2361.956775,2360.083729,2378.251725,2374.093987,2372.699179,2355.788788,2361.956775,2361.066147,...,2355.168952,2350.812653,2354.201535,2368.498071,2368.096015,2344.869655,2355.168952,2352.457341,2355.168952,2349.198187
44638,2378.123366,2378.720556,2363.842782,2362.002380,2368.568817,2374.353238,2373.760552,2357.668860,2363.842782,2362.982489,...,2352.947005,2348.389288,2351.468713,2368.473856,2368.612726,2342.397342,2352.947005,2350.347309,2352.947005,2346.753160
44639,2374.662834,2375.666419,2357.737060,2355.683437,2362.149755,2371.768827,2371.445673,2351.491371,2357.737060,2356.916690,...,2361.530329,2358.183755,2353.803893,2372.652522,2372.809565,2354.149282,2361.530329,2358.928047,2361.535132,2356.402632

In [13]:
# creating input grid dataframe
input_player_df = pd.DataFrame()

In [14]:
directory = r"C:\Users\aniss\grid-edge\data\summer\input_csv\aug"

for filename in os.listdir(directory):
    if str(filename).startswith('25.csv'):
        continue
    player = pd.read_csv(os.path.join(directory, filename))
    player['grid'] = player['grid'].str.replace("i", "j").apply(lambda x: complex(x))
    node_id = player['id'].loc[0]
    column_name_p = 'p_'+str(node_id)
    column_name_q = 'q_'+str(node_id)
#change .head() value to target dataframe row number
    input_player_df[column_name_p] = player['grid'].apply(lambda x: x.real).head(44640)
    input_player_df[column_name_q] = player['grid'].apply(lambda x: x.imag).head(44640)

In [15]:
input_player_df

,p_1,q_1,p_10,q_10,p_11,q_11,p_12,q_12,p_13,q_13,...,p_5,q_5,p_6,q_6,p_7,q_7,p_8,q_8,p_9,q_9
0,43770.0,16469.310048,49815.0,22403.753687,6210.0,2695.012019,7680.0,3179.099513,61020.0,29502.531393,...,53790.0,25326.903353,67515.0,31808.368293,29070.0,10529.067416,6045.0,2515.278484,5310.0,2237.349195
1,43800.0,16489.442538,49830.0,18118.185743,6210.0,2652.451633,7410.0,3283.708947,60975.0,25982.549038,...,53640.0,18459.901687,67395.0,27014.072442,39240.0,14900.141805,6090.0,2647.371431,5295.0,2050.646953
2,43740.0,18093.970905,49980.0,16776.366378,6210.0,2155.374490,7410.0,2942.624906,95295.0,39878.190122,...,53670.0,21365.140495,67035.0,31328.887859,39525.0,16323.012981,6165.0,2984.864340,5265.0,2429.566369
3,43695.0,20767.052779,49920.0,19616.208244,6210.0,2420.677435,7410.0,2509.893336,111255.0,50618.963361,...,53565.0,23865.960887,67005.0,32052.445552,39675.0,13387.876143,8325.0,4010.588460,5280.0,1755.293115
4,43635.0,16530.779025,49875.0,22098.446062,6210.0,2789.715225,8385.0,3529.459545,105225.0,38872.747755,...,53520.0,18590.917043,67050.0,29373.794538,39645.0,15676.843795,7950.0,3506.616212,5265.0,1780.150155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44635,6720.0,2783.210231,52035.0,24418.630981,72225.0,28203.239226,7695.0,3620.339227,6930.0,2692.723848,...,54600.0,19755.024567,70620.0,33218.534846,40200.0,19088.771038,5775.0,2554.586466,7305.0,3011.122825
44636,5550.0,2539.380180,51960.0,24852.282395,72255.0,26619.217900,7920.0,2863.564594,6195.0,2286.259900,...,54690.0,20617.117340,70425.0,29445.121614,40395.0,16284.382985,4815.0,1931.008371,7185.0,3239.030520
44637,5535.0,2377.145083,51870.0,23536.594064,72210.0,28591.535057,7890.0,2850.166224,6210.0,2648.898031,...,54660.0,21157.921748,70515.0,33171.664766,40545.0,17106.067338,4800.0,1607.936207,7140.0,3206.669993
44638,5535.0,2511.753480,51870.0,23979.794916,40785.0,17449.052683,7830.0,3075.092810,6225.0,2808.420788,...,54765.0,21260.283351,70425.0,24380.417452,14040.0,5889.002648,4800.0,1907.035168,7155.0,2937.867317
44639,5550.0,2401.784284,51825.0,19060.016572,25500.0,11404.569433,7935.0,3088.602381,6180.0,2872.144530,...,54555.0,23807.403348,70545.0,23658.398890,8730.0,3479.767501,4800.0,2054.864040,7155.0,2892.343938

# Concat all Summer Data

In [2]:
def DPMU(phase,dpmu_data,phase_letter,letter):
    for (columnName, columnData) in phase.iteritems():
        i=0
        if 'Meter' in columnName:
            split = columnName.split('Meter')
            house_name = f'Meter{letter}_'+ split[1]
            i+=1
            dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
            dpmu_data[house_name] = dpmu_values
        else:
            split_column_names = columnName.split('_')
            house_name = 'house'+str(split_column_names[phase_letter])
            dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
            dpmu_data[house_name] = dpmu_values
    return dpmu_data

In [3]:
def Input(month,input_player_df):
    directory = fr'C:\Users\aniss\grid-edge\data\summer\input_csv\{month}'

    for filename in os.listdir(directory):
        if str(filename).startswith('25.csv'):
            continue
        player = pd.read_csv(os.path.join(directory, filename))
        player['grid'] = player['grid'].str.replace("i", "j").apply(lambda x: complex(x))
        node_id = player['id'].loc[0]
        column_name_p = 'p_'+str(node_id)
        column_name_q = 'q_'+str(node_id)
    #change .head() value to target dataframe row number
        input_player_df[column_name_p] = player['grid'].apply(lambda x: x.real).head(44640)
        input_player_df[column_name_q] = player['grid'].apply(lambda x: x.imag).head(44640)
    return input_player_df

In [4]:
dpmu_phaseA_aug = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\aug\multi_voltageA.csv')
dpmu_phaseB_aug = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\aug\multi_voltageB.csv')
dpmu_phaseC_aug = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\aug\multi_voltageC.csv')

dpmu_phaseA_july = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\july\multi_voltageA.csv')
dpmu_phaseB_july = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\july\multi_voltageB.csv')
dpmu_phaseC_july = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\july\multi_voltageC.csv')

dpmu_phaseA_june = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\june\multi_voltageA.csv')
dpmu_phaseB_june = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\june\multi_voltageB.csv')
dpmu_phaseC_june = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\june\multi_voltageC.csv')

dpmu_phaseA_sept = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\sept\multi_voltageA.csv')
dpmu_phaseB_sept = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\sept\multi_voltageB.csv')
dpmu_phaseC_sept = pd.read_csv(r'C:\Users\aniss\grid-edge\data\summer\targets\trimmed_targets\sept\multi_voltageC.csv')

In [5]:
dpmu_phaseA_aug = dpmu_phaseA_aug.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseB_aug = dpmu_phaseB_aug.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseC_aug = dpmu_phaseC_aug.drop(['Meter5', '# timestamp'], axis=1)

dpmu_phaseA_july = dpmu_phaseA_july.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseB_july = dpmu_phaseB_july.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseC_july = dpmu_phaseC_july.drop(['Meter5', '# timestamp'], axis=1)

dpmu_phaseA_june = dpmu_phaseA_june.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseB_june = dpmu_phaseB_june.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseC_june = dpmu_phaseC_june.drop(['Meter5', '# timestamp'], axis=1)

dpmu_phaseA_sept = dpmu_phaseA_sept.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseB_sept = dpmu_phaseB_sept.drop(['Meter5', '# timestamp'], axis=1)
dpmu_phaseC_sept = dpmu_phaseC_sept.drop(['Meter5', '# timestamp'], axis=1)

In [6]:
phaseA = 0
phaseB = 1
phaseC = 2
A = "A"
B = "B"
C = "C"

In [7]:
dpmu_data_aug = pd.DataFrame()
dpmu_data_july = pd.DataFrame()
dpmu_data_june = pd.DataFrame()
dpmu_data_sept = pd.DataFrame()

In [8]:
dpmu_data_aug = DPMU(dpmu_phaseA_aug,dpmu_data_aug,phaseA, A)
dpmu_data_aug = DPMU(dpmu_phaseB_aug,dpmu_data_aug, phaseB, B)
dpmu_data_aug = DPMU(dpmu_phaseC_aug,dpmu_data_aug, phaseC, C)

dpmu_data_july = DPMU(dpmu_phaseA_aug,dpmu_data_july,phaseA, A)
dpmu_data_july = DPMU(dpmu_phaseB_aug,dpmu_data_july, phaseB, B)
dpmu_data_july = DPMU(dpmu_phaseC_aug,dpmu_data_july, phaseC, C)

dpmu_data_june = DPMU(dpmu_phaseA_aug,dpmu_data_june,phaseA, A)
dpmu_data_june = DPMU(dpmu_phaseB_aug,dpmu_data_june, phaseB, B)
dpmu_data_june = DPMU(dpmu_phaseC_aug,dpmu_data_june, phaseC, C)

dpmu_data_sept = DPMU(dpmu_phaseA_aug,dpmu_data_sept,phaseA, A)
dpmu_data_sept = DPMU(dpmu_phaseB_aug,dpmu_data_sept, phaseB, B)
dpmu_data_sept = DPMU(dpmu_phaseC_aug,dpmu_data_sept, phaseC, C)

In [9]:
dpmu_data = pd.DataFrame()
dpmu_data = pd.concat([dpmu_data_aug, dpmu_data_july,dpmu_data_june,dpmu_data_sept], ignore_index = True)

In [10]:
dpmu_data

,MeterA_2,MeterA_1,MeterA_3,MeterA_4,housenode1,housenode4,housenode7,housenode13,housenode10,housenode22,...,MeterC_3,MeterC_4,house3,house6,house9,house15,house12,house24,house21,house18
0,2376.409889,2378.388636,2361.400016,2357.538734,2363.994761,2376.991693,2375.718498,2352.767045,2361.400016,2361.418434,...,2347.430794,2343.286737,2366.926658,2366.504003,2366.229047,2337.377650,2347.430794,2344.827519,2347.430794,2342.868207
1,2380.907281,2382.797347,2371.481343,2369.147260,2369.150113,2380.564999,2378.824397,2364.411194,2371.481343,2371.381328,...,2350.315321,2346.584561,2368.194516,2368.069600,2367.731763,2340.824483,2350.315321,2347.744618,2350.315321,2346.217019
2,2377.256861,2379.415364,2366.150157,2362.635628,2365.298299,2377.165092,2375.486746,2355.295777,2366.150157,2365.965524,...,2347.366674,2343.390828,2368.214272,2367.751656,2367.378270,2337.614698,2347.366674,2344.726159,2347.366674,2343.008353
3,2374.778306,2376.835701,2360.276611,2355.968593,2363.462683,2374.634968,2372.936101,2347.306906,2360.276611,2360.103638,...,2346.915101,2342.973333,2368.147718,2367.509425,2367.188528,2337.128129,2346.915101,2344.249188,2346.915101,2342.826055
4,2374.294670,2376.486046,2360.364542,2356.340245,2361.685581,2374.155190,2372.415367,2348.156111,2360.364542,2360.259043,...,2350.219551,2346.321728,2370.321920,2369.072138,2368.743645,2340.504174,2350.219551,2347.680284,2350.219551,2346.162014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178555,2376.630616,2376.909727,2361.718523,2361.061229,2374.703288,2370.727952,2368.923606,2360.530336,2361.718523,2361.017211,...,2376.217110,2375.946268,2383.319090,2379.381705,2378.958603,2374.796995,2376.217110,2373.572793,2376.221997,2376.308574
178556,2381.644845,2381.834449,2370.206272,2369.488276,2379.981534,2375.998877,2374.364148,2369.098087,2370.206272,2370.419822,...,2382.110171,2382.447797,2385.851997,2382.892900,2382.408382,2381.193939,2382.110171,2379.197792,2382.110171,2382.637122
178557,2381.528614,2381.678165,2370.588511,2369.942255,2379.996042,2375.550753,2373.865940,2369.552048,2370.588511,2370.952665,...,2380.265189,2380.322989,2384.808413,2381.982941,2381.508342,2379.068204,2380.265189,2377.242809,2380.265189,2380.224830
178558,2385.661751,2385.851792,2375.602828,2374.996127,2383.999001,2381.842079,2381.343812,2374.606052,2375.602828,2375.908193,...,2372.551226,2372.458286,2380.764987,2377.501090,2377.154748,2371.196825,2372.551226,2369.488739,2372.551226,2372.230925
178559,2385.947920,2386.321254,2376.483367,2375.827077,2384.424349,2382.859673,2382.570365,2375.446792,2376.483367,2376.738342,...,2373.122160,2373.005032,2383.055426,2379.361139,2379.068573,2371.733831,2373.122160,2370.110261,2373.122160,2372.751463

In [11]:
dpmu_data_2 = dpmu_data[0:175680]

In [12]:
aug = "aug"
july = "july"
june = "june"
sept = "sept"

In [13]:
input_player_df_aug = pd.DataFrame()
input_player_df_july = pd.DataFrame()
input_player_df_june = pd.DataFrame()
input_player_df_sept = pd.DataFrame()

In [15]:
input_player_df_aug = Input(aug,input_player_df_aug)
input_player_df_july = Input(july,input_player_df_july)
input_player_df_june = Input(june,input_player_df_june)
input_player_df_sept = Input(sept,input_player_df_sept)

In [16]:
input_player_df = pd.DataFrame()
input_player_df = pd.concat([input_player_df_aug,input_player_df_july,input_player_df_june,input_player_df_sept], ignore_index=True)

In [17]:
input_player_df

,p_1,q_1,p_10,q_10,p_11,q_11,p_12,q_12,p_13,q_13,...,p_5,q_5,p_6,q_6,p_7,q_7,p_8,q_8,p_9,q_9
0,43770.0,18273.479083,49815.0,19677.968025,6210.0,2993.529277,7680.0,2977.205699,61020.0,25629.453761,...,53790.0,22680.824631,67515.0,26725.875676,29070.0,12766.083147,6045.0,2538.376656,5310.0,1768.574303
1,43800.0,16056.165241,49830.0,21169.506826,6210.0,2503.047231,7410.0,3187.775742,60975.0,24463.259976,...,53640.0,18591.367838,67395.0,24229.587465,39240.0,16830.434105,6090.0,2080.689498,5295.0,1960.017239
2,43740.0,16725.190261,49980.0,18571.507872,6210.0,2406.866873,7410.0,3368.241776,95295.0,34245.168859,...,53670.0,17841.890713,67035.0,23688.227789,39525.0,14630.069312,6165.0,2053.104821,5265.0,2332.545638
3,43695.0,14533.893706,49920.0,21483.136368,6210.0,2552.831448,7410.0,2727.305834,111255.0,45610.401766,...,53565.0,25357.082993,67005.0,25112.807910,39675.0,15125.471091,8325.0,3691.961411,5280.0,1817.387203
4,43635.0,18926.971373,49875.0,19129.801554,6210.0,2285.612698,8385.0,2785.115072,105225.0,42562.705246,...,53520.0,24179.304713,67050.0,27466.505811,39645.0,16417.639968,7950.0,2996.814233,5265.0,2177.816589
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175675,6465.0,2822.317617,45765.0,18524.166195,50505.0,22528.098381,8430.0,2789.272489,57450.0,25219.495588,...,4650.0,1807.317228,64635.0,27118.997672,4740.0,1824.514606,41190.0,13817.778604,6705.0,2637.722707
175676,7725.0,3085.881665,45735.0,20028.965065,24030.0,10193.354166,23640.0,10681.441361,57855.0,25297.044348,...,4635.0,1981.916417,62775.0,29347.144545,4725.0,1975.152094,39915.0,16853.690903,6645.0,2488.146655
175677,7650.0,3636.386829,45810.0,17385.362109,18000.0,6288.798710,38730.0,16854.617167,59265.0,23744.529706,...,4635.0,2003.650515,62595.0,29119.896786,3105.0,1308.767508,39375.0,18577.764183,6645.0,2787.186256
175678,7635.0,2981.949705,46065.0,18604.384766,8415.0,2868.802547,39315.0,18257.810943,58860.0,21173.453924,...,4620.0,1985.184652,61470.0,25781.111189,2745.0,1154.465979,39315.0,16184.443484,6645.0,3169.747109
175679,7605.0,3395.411874,46575.0,19378.503093,8445.0,3105.556188,39855.0,19252.321813,57000.0,20934.798257,...,4620.0,2040.929601,60735.0,23555.123783,2745.0,1325.179165,22200.0,8930.327131,6630.0,2417.592250

# Linear Model Training

In [28]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedKFold
from sklearn.linear_model import LinearRegression, Ridge, Lasso, LogisticRegression, SGDRegressor, ElasticNet, RidgeCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import xgboost as xgb
from pylab import *

In [29]:
# splitting data into train and test datasets
X = input_player_df.copy()
y = dpmu_data_2.copy()
    
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [19]:
y_test.shape

(57975, 36)

# Ridge with all data and fixed MSE

In [30]:
#trains the model with the original data
model = Ridge()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [21]:
y_pred

array([[2372.53773225, 2373.98736745, 2354.33776726, ..., 2367.35272085,
        2368.23812618, 2365.29042231],
       [2372.34787758, 2373.70537034, 2354.22683813, ..., 2342.34251149,
        2344.36681273, 2338.68086665],
       [2386.80430667, 2388.35112842, 2380.30013139, ..., 2380.93265601,
        2381.87597001, 2380.27010138],
       ...,
       [2383.46719298, 2383.84705896, 2368.96041311, ..., 2343.75779477,
        2344.95907144, 2338.62658131],
       [2393.56463048, 2394.10761011, 2388.78790503, ..., 2376.21359117,
        2377.05753023, 2374.14414343],
       [2396.35984016, 2396.84049816, 2394.58105487, ..., 2376.87401157,
        2377.84561545, 2375.29515463]])

In [22]:
#saves the column names to make the y_pred df
names = y_test.columns

In [33]:
#creates df
df_y_pred = pd.DataFrame(y_pred,columns = names)

In [24]:
df_y_pred

,MeterA_2,MeterA_1,MeterA_3,MeterA_4,housenode1,housenode4,housenode7,housenode13,housenode10,housenode22,...,MeterC_3,MeterC_4,house3,house6,house9,house15,house12,house24,house21,house18
0,2372.537732,2373.987367,2354.337767,2351.702369,2361.199854,2370.137162,2369.282207,2348.043860,2354.337767,2353.603281,...,2368.239033,2366.228289,2367.446276,2372.128493,2371.085344,2363.624885,2368.239033,2367.352721,2368.238126,2365.290422
1,2372.347878,2373.705370,2354.226838,2351.441493,2358.547997,2368.990484,2367.889859,2348.231441,2354.226838,2353.431553,...,2344.368073,2340.376577,2344.927283,2356.665664,2355.132662,2335.402137,2344.368073,2342.342511,2344.366813,2338.680867
2,2386.804307,2388.351128,2380.300131,2378.692544,2376.230476,2387.263053,2387.038576,2376.406911,2380.300131,2380.155825,...,2381.876597,2380.624423,2383.223827,2387.283844,2386.864501,2378.958608,2381.876597,2380.932656,2381.875970,2380.270101
3,2397.849428,2397.747777,2396.218828,2395.136198,2395.729857,2397.047651,2397.291389,2394.627683,2396.218828,2395.598104,...,2360.566974,2359.343727,2373.017173,2379.048792,2378.888289,2359.047976,2360.566974,2358.526865,2360.565784,2358.378493
4,2385.649539,2386.161780,2372.238268,2369.949337,2377.588085,2384.440330,2384.139425,2366.589795,2372.238268,2371.669503,...,2349.416308,2346.138001,2353.403131,2361.807503,2360.435109,2342.061894,2349.416308,2348.220110,2349.415408,2345.080994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57970,2379.572925,2380.842214,2365.968136,2363.381243,2370.502029,2378.329793,2377.906438,2360.301721,2365.968136,2364.935633,...,2367.267710,2365.326681,2372.287706,2374.195586,2373.505576,2362.868077,2367.267710,2366.178228,2367.266736,2364.635803
57971,2392.710396,2393.118566,2386.424619,2384.958926,2386.308763,2392.449041,2392.484286,2383.706683,2386.424619,2386.216444,...,2363.853533,2361.859817,2367.659734,2376.672778,2375.702398,2359.320096,2363.853533,2363.047671,2363.852915,2361.092685
57972,2383.467193,2383.847059,2368.960413,2366.011593,2375.703065,2381.668330,2381.505566,2362.200571,2368.960413,2368.016962,...,2344.960113,2340.875550,2351.399599,2361.255764,2359.611195,2337.000489,2344.960113,2343.757795,2344.959071,2338.626581
57973,2393.564630,2394.107610,2388.787905,2387.801338,2388.987936,2393.635752,2393.710197,2386.322877,2388.787905,2388.691423,...,2377.058119,2374.977798,2383.182626,2385.970599,2385.506583,2372.345957,2377.058119,2376.213591,2377.057530,2374.144143
57974,2396.359840,2396.840498,2394.581055,2394.261314,2393.113914,2396.649742,2396.731752,2393.246772,2394.581055,2394.760793,...,2377.846000,2376.397068,2385.555306,2386.794755,2386.663999,2376.469398,2377.846000,2376.874012,2377.845615,2375.295155

In [25]:
#concatenate both y's so we can scale with respect to both ranges
scaling_all = pd.concat([y_test,df_y_pred], keys=['y_test','y_pred'])

In [31]:
scaling_all.xs('y_pred')

,MeterA_2,MeterA_1,MeterA_3,MeterA_4,house1,house4,house7,house13,house10,house22,...,MeterC_3,MeterC_4,house3,house6,house9,house15,house12,house24,house21,house18
0,2374.317007,2375.489660,2355.961090,2353.255963,2362.963754,2372.052137,2371.384152,2349.412033,2355.961090,2355.349741,...,2355.025164,2351.622513,2356.447601,2364.005149,2362.556663,2347.776313,2355.025164,2353.912832,2355.024259,2350.165139
1,2376.219662,2377.406155,2359.103911,2356.151059,2363.375255,2373.938011,2373.227957,2352.507280,2359.103911,2358.263421,...,2339.914037,2335.913013,2343.716806,2354.480408,2352.564663,2331.260108,2339.914037,2338.085182,2339.912737,2334.217181
2,2388.698542,2389.917540,2382.729947,2381.444219,2380.241137,2388.533551,2388.170586,2379.766645,2382.729947,2382.469987,...,2375.142516,2373.577888,2379.938075,2381.879609,2381.356776,2371.400738,2375.142516,2373.999199,2375.141805,2373.100127
3,2402.748964,2402.737484,2404.939159,2404.186565,2399.987806,2403.313779,2403.907636,2402.812876,2404.939159,2404.372723,...,2359.076163,2357.048676,2372.834417,2378.738249,2378.427235,2355.823359,2359.076163,2357.498285,2359.075374,2355.916026
4,2384.176247,2384.951639,2372.038059,2369.780409,2375.208597,2382.691288,2382.379072,2366.889727,2372.038059,2371.405858,...,2355.645230,2352.793740,2359.241653,2367.046111,2365.735251,2349.574588,2355.645230,2354.389305,2355.644296,2351.523140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57970,2378.444530,2379.633784,2363.224065,2360.852944,2368.364225,2376.792479,2376.173264,2357.625663,2363.224065,2362.592228,...,2359.208240,2356.551152,2363.149599,2367.320489,2366.065757,2353.196731,2359.208240,2357.783580,2359.207257,2355.572384
57971,2394.848397,2395.179078,2390.822126,2389.601596,2389.999341,2394.754463,2394.984706,2387.947764,2390.822126,2390.429376,...,2368.216453,2366.203699,2374.779989,2380.685767,2380.163482,2364.544770,2368.216453,2367.496453,2368.216006,2365.166033
57972,2390.007060,2390.135910,2380.417983,2378.260838,2384.314354,2389.064463,2389.259824,2375.466122,2380.417983,2379.772640,...,2353.417389,2350.248786,2360.059342,2369.384140,2368.120908,2347.549678,2353.417389,2352.326057,2353.416640,2348.632099
57973,2391.989751,2392.613503,2386.518176,2385.284171,2386.624684,2391.708634,2391.617495,2383.769035,2386.518176,2386.318899,...,2377.110305,2375.620293,2381.924059,2385.063705,2384.658246,2374.030698,2377.110305,2376.183773,2377.109754,2374.940122
57974,2394.101119,2394.340096,2388.854518,2387.834132,2391.846254,2394.285826,2394.475257,2386.403102,2388.854518,2388.931574,...,2383.088876,2381.690825,2387.944654,2389.802582,2389.505211,2380.404710,2383.088876,2382.366371,2383.088659,2381.080859

In [32]:
#scaling the df
scaler = StandardScaler()
scaler.fit(scaling_all)
#scaler.transform(scaling_df)

StandardScaler()

In [33]:
#storing scaled values into a df
scaledDF = pd.DataFrame(scaler.transform(scaling_all),columns = names)

In [34]:
#splitting df back into the y_pred and y_test
scaled_y_pred = scaledDF[:57975]
scaled_y_test = scaledDF[57975:]

In [ ]:
#finding L2 norm of the y_test_scaled vectors
# L2_ratios = []
# for index, row in scaled_y_test.iterrows():
#     L2_ratios.append(LA.norm(row))

In [31]:
#UPDATED VERSION
L2_ratios = []
for index, row in y_test.iterrows():
    L2_ratios.append(LA.norm(row))

In [ ]:
#dividing all y_pred by the L2 ratios:
# ratio_index = 0
# scaled_ratio_y_pred = []
# for index, row in scaled_y_pred.iterrows():
#     scaled_ratio_y_pred.append(row/L2_ratios[ratio_index])
#     ratio_index += 1

# scaled_ratio_y_pred

In [ ]:
#UPDATED dividing all y_pred by the L2 ratios:
ratio_index = 0
L2_norm_y_pred = []
for index, row in df_y_pred.iterrows():
    L2_norm_y_pred.append(row/L2_ratios[ratio_index])
    ratio_index += 1

L2_norm_y_pred

In [41]:
df_L2_norm_y_pred = pd.DataFrame(L2_norm_y_pred, columns = names)
df_L2_norm_y_pred

,MeterA_2,MeterA_1,MeterA_3,MeterA_4,housenode1,housenode4,housenode7,housenode13,housenode10,housenode22,...,MeterC_3,MeterC_4,house3,house6,house9,house15,house12,house24,house21,house18
0,0.166854,0.166956,0.165574,0.165389,0.166057,0.166685,0.166625,0.165132,0.165574,0.165523,...,0.166552,0.166411,0.166496,0.166825,0.166752,0.166227,0.166552,0.166490,0.166552,0.166345
1,0.167121,0.167217,0.165844,0.165648,0.166149,0.166884,0.166807,0.165422,0.165844,0.165788,...,0.165150,0.164869,0.165189,0.166016,0.165908,0.164518,0.165150,0.165007,0.165150,0.164749
2,0.167030,0.167138,0.166575,0.166462,0.166290,0.167062,0.167047,0.166302,0.166575,0.166565,...,0.166685,0.166598,0.166780,0.167064,0.167034,0.166481,0.166685,0.166619,0.166685,0.166573
3,0.167713,0.167706,0.167599,0.167524,0.167565,0.167657,0.167674,0.167488,0.167599,0.167556,...,0.165106,0.165020,0.165976,0.166398,0.166387,0.164999,0.165106,0.164963,0.165106,0.164953
4,0.167824,0.167860,0.166881,0.166720,0.167257,0.167739,0.167718,0.166483,0.166881,0.166841,...,0.165275,0.165045,0.165556,0.166147,0.166050,0.164758,0.165275,0.165191,0.165275,0.164970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57970,0.166493,0.166582,0.165541,0.165360,0.165858,0.166406,0.166376,0.165145,0.165541,0.165469,...,0.165632,0.165496,0.165983,0.166117,0.166068,0.165324,0.165632,0.165556,0.165632,0.165448
57971,0.166851,0.166880,0.166413,0.166311,0.166405,0.166833,0.166835,0.166223,0.166413,0.166398,...,0.164839,0.164700,0.165104,0.165733,0.165665,0.164523,0.164839,0.164783,0.164839,0.164646
57972,0.167140,0.167167,0.166123,0.165916,0.166595,0.167014,0.167002,0.165649,0.166123,0.166057,...,0.164440,0.164153,0.164891,0.165582,0.165467,0.163881,0.164440,0.164355,0.164440,0.163996
57973,0.166990,0.167028,0.166657,0.166588,0.166671,0.166995,0.167000,0.166485,0.166657,0.166650,...,0.165838,0.165693,0.166266,0.166460,0.166428,0.165510,0.165838,0.165780,0.165838,0.165635
57974,0.167136,0.167170,0.167012,0.166990,0.166910,0.167157,0.167162,0.166919,0.167012,0.167025,...,0.165845,0.165744,0.166383,0.166469,0.166460,0.165749,0.165845,0.165777,0.165845,0.165667

In [ ]:
#UPDATED dividing all y_pred by the L2 ratios:
norm_index = 0
L2_norm_y_test = []
for index, row in y_test.iterrows():
    L2_norm_y_test.append(row/L2_ratios[norm_index])
    norm_index += 1

L2_norm_y_test

In [42]:
df_L2_norm_y_test = pd.DataFrame(L2_norm_y_test, columns = names)
df_L2_norm_y_test

,MeterA_2,MeterA_1,MeterA_3,MeterA_4,housenode1,housenode4,housenode7,housenode13,housenode10,housenode22,...,MeterC_3,MeterC_4,house3,house6,house9,house15,house12,house24,house21,house18
77792,0.167688,0.167755,0.167013,0.166907,0.167400,0.167561,0.167572,0.166590,0.167013,0.166999,...,0.164882,0.164475,0.166587,0.166155,0.166056,0.164066,0.164882,0.164725,0.164882,0.164250
90527,0.168458,0.168509,0.167739,0.167659,0.167535,0.168412,0.168477,0.167534,0.167739,0.167636,...,0.163899,0.163723,0.163704,0.164775,0.164527,0.163612,0.163899,0.163736,0.163899,0.163545
98212,0.167580,0.167747,0.168024,0.168025,0.166701,0.167693,0.167687,0.167973,0.168024,0.167946,...,0.165482,0.165278,0.166823,0.166897,0.166885,0.164901,0.165482,0.165315,0.165482,0.165258
2319,0.167504,0.167478,0.167472,0.167436,0.167530,0.167296,0.167270,0.167537,0.167472,0.167427,...,0.165311,0.165324,0.166356,0.166906,0.166991,0.165500,0.165311,0.165143,0.165311,0.165251
167012,0.167837,0.167777,0.166735,0.166734,0.167608,0.167438,0.167347,0.166682,0.166735,0.166675,...,0.165499,0.165289,0.164910,0.166015,0.165912,0.165214,0.165499,0.165506,0.165499,0.165059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78250,0.165686,0.165762,0.164055,0.163757,0.164907,0.165510,0.165506,0.163465,0.164055,0.164086,...,0.167073,0.166969,0.166395,0.167149,0.167168,0.166811,0.167073,0.167077,0.167073,0.166966
87210,0.167536,0.167560,0.167419,0.167388,0.167472,0.167661,0.167766,0.167512,0.167419,0.167403,...,0.166491,0.166636,0.166735,0.166485,0.166360,0.166882,0.166491,0.166549,0.166491,0.166680
86003,0.167284,0.167307,0.166619,0.166476,0.166845,0.167050,0.166982,0.166235,0.166619,0.166641,...,0.164073,0.163746,0.165005,0.165822,0.165830,0.163473,0.164073,0.163993,0.164074,0.163611
146337,0.167413,0.167380,0.167564,0.167436,0.167450,0.167309,0.167241,0.167248,0.167564,0.167499,...,0.164227,0.164053,0.165658,0.166139,0.166161,0.164302,0.164227,0.164155,0.164227,0.163804
91323,0.167109,0.167116,0.166667,0.166681,0.167201,0.167280,0.167360,0.166699,0.166667,0.166699,...,0.166299,0.166315,0.167086,0.166857,0.166750,0.166370,0.166299,0.166110,0.166300,0.166316

In [39]:
print("MSE: ", (mean_squared_error(L2_norm_y_test, L2_norm_y_pred)))

MSE:  1.2430175428984975e-06

## Ordinary Least Squares

In [26]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

scaler = StandardScaler()
scaler.fit(y_pred)
scaler.transform(y_pred)

scaler_test = StandardScaler()
scaler_test.fit(y_test)
scaler_test.transform(y_test)

print("MSE: ", (mean_squared_error(scaler_test.transform(y_test), scaler_pred.transform(y_pred))))

MSE:  1.0158591891989472

In [115]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("MSE: ", (mean_squared_error(y_test, y_pred)))

MSE:  0.012124357406555458

In [36]:
y_test

array([[0.43024622, 0.42986057, 0.44234119, ..., 0.45515354, 0.45854115,
        0.46895496],
       [0.69990555, 0.71149465, 0.73133722, ..., 0.55384852, 0.54961779,
        0.55760762],
       [0.82572067, 0.81447713, 0.84282362, ..., 0.45870779, 0.46482167,
        0.46502154],
       ...,
       [0.5397708 , 0.53871576, 0.55593516, ..., 0.52208204, 0.51849853,
        0.52254762],
       [0.67406778, 0.65523436, 0.64788456, ..., 0.73079766, 0.7247211 ,
        0.7325962 ],
       [0.39451788, 0.38331792, 0.36218836, ..., 0.58653476, 0.58105477,
        0.59045469]])

In [39]:
y_pred

array([[0.46029834, 0.45509918, 0.44810196, ..., 0.49324218, 0.48917813,
        0.49612703],
       [0.59275047, 0.59725945, 0.61237036, ..., 0.62708905, 0.6269492 ,
        0.63609951],
       [0.76315693, 0.75296435, 0.76081399, ..., 0.6191779 , 0.6231838 ,
        0.63001511],
       ...,
       [0.59252091, 0.59247304, 0.58884076, ..., 0.54180885, 0.54037541,
        0.55271366],
       [0.64564669, 0.63943248, 0.64425246, ..., 0.72264428, 0.72011022,
        0.7210659 ],
       [0.57946729, 0.57699505, 0.57853069, ..., 0.51783075, 0.5222306 ,
        0.53818593]])

In [ ]:
# normalise data
# use rmse and scale it to the original signal -> what is the magnitude of the signal we are trying to predict
# every sample is 24x1 -> what is the average norm of that vector? -> how to evaluate error of model
# mse grows linearly with inputs

In [23]:
y_pred.shape

(14732, 36)

## Lasso Model

In [37]:
model = Lasso()

model.fit(X_train, y_train)
        
y_pred = model.predict(X_test)
print(mean_squared_error(y_test, y_pred))

0.0171241204202973

## Ridge Model

In [116]:
model = Ridge()
model.fit(X_train, y_train)
        
y_pred = model.predict(X_test)
print(mean_squared_error(y_test, y_pred))

0.012124322218466712

In [40]:
model = RidgeCV(alphas=[1e-3, 1e-2, 1e-1, 1]).fit(X_train, y_train)
y_pred = model.predict(X_test)
print(mean_squared_error(y_test, y_pred))

0.010152678682675316

## Elastic Net with Cross Validation and Hyperparameter Tuning

In [44]:
model = ElasticNet()

# define model evaluation method
cv = RepeatedKFold(n_splits=3, n_repeats=3, random_state=1)
# define grid
grid = dict()
grid['alpha'] = [1e-2, 1e-1, 1]
grid['l1_ratio'] = arange(0, 1, 0.1)
# define search
search = GridSearchCV(model, grid, scoring='neg_mean_squared_error', cv=cv, n_jobs=-1)
# perform the search
results = search.fit(X_train, y_train)
# summarize
print('MSE: %.3f' % results.best_score_)
print('Config: %s' % results.best_params_)

In [42]:
model = ElasticNet()

In [43]:
model = ElasticNet(alpha=100, l1_ratio=0.0)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("MSE: ", mean_squared_error(y_test, y_pred))

C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 251.82952949721698, tolerance: 0.05041201135548906
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 246.45765555344084, tolerance: 0.04933683279040945
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 266.86680688287987, tolerance: 0.05342448643325658
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 255.57731710229797, tolerance: 0.051164853920694586
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 348.5959557285708, tolerance: 0.06979173770822632
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 251.0560505360056, tolerance: 0.0502599162083866
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 251.60659589026267, tolerance: 0.05037057339905545
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 248.30063259023427, tolerance: 0.04970889855968858
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 270.4935736594981, tolerance: 0.05415140883875635
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 266.8758603374802, tolerance: 0.05342630008065377
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 254.45702890868998, tolerance: 0.05094110248401249
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 182.76993012905896, tolerance: 0.03655885062325224
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 187.17987960622705, tolerance: 0.03744111692567943
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 185.23384587116507, tolerance: 0.037052336741708394
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 192.70929807944606, tolerance: 0.03854748829687261
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 224.35681865664824, tolerance: 0.04488455760615869
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 195.82961801026588, tolerance: 0.03917118880269752
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 196.05005779251647, tolerance: 0.03921527078452287
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 197.3505576454725, tolerance: 0.039475200544262866
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 184.39832506809392, tolerance: 0.03688512258285307
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 185.23635285998307, tolerance: 0.037052838089658535
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 202.16938033884495, tolerance: 0.04044029109111813
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 338.80152701641066, tolerance: 0.06785352736892307
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 341.6831657463027, tolerance: 0.06842842822025764
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 287.42338911586666, tolerance: 0.05755048742892406
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 281.80942741955545, tolerance: 0.056426093934310875
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 320.4964823607384, tolerance: 0.06418996881972729
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 340.9315885022142, tolerance: 0.0682855439640901
  model = cd_fast.enet_coordinate_descent(

C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 333.39574314100304, tolerance: 0.0667765930407424
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 288.65864528996906, tolerance: 0.05779873249115196
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 292.56381116999387, tolerance: 0.05857850176737018
  model = cd_fast.enet_coordinate_descent(
C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 287.43252122054, tolerance: 0.057552316238576304
  model = cd_fast.enet_coordinate_descent(

MSE:  0.017094343589100527

C:\Users\aniss\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 275.8723096034738, tolerance: 0.0552368007903797
  model = cd_fast.enet_coordinate_descent(

# Neural Network

In [ ]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_regression
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# get the dataset
def get_dataset():
    X, y = input_player_df.copy().to_numpy(), dpmu_data.copy().to_numpy()
    return X, y

In [ ]:
# get the model
def get_model(n_inputs, n_outputs):
    model = Sequential()
    model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
    model.add(Dense(n_outputs))
    model.compile(loss='mse', optimizer='adam')
    return model

In [ ]:
# evaluate a model using repeated k-fold cross-validation
def evaluate_model(X, y):
    results = list()
    n_inputs, n_outputs = X.shape[1], y.shape[1]
    # define evaluation procedure
    cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
    # enumerate folds
    for train_ix, test_ix in cv.split(X):
        # prepare data
        X_train, X_test = X[train_ix], X[test_ix]
        y_train, y_test = y[train_ix], y[test_ix]
        # define model
        model = get_model(n_inputs, n_outputs)
        # fit model
        model.fit(X_train, y_train, verbose=0, epochs=100)
        # evaluate model on test set
        mse = model.evaluate(X_test, y_test, verbose=0)
        # store result
        print(mse)
        results.append(mse)
        return results

In [ ]:
# load dataset
X, y = get_dataset()
# evaluate model
results = evaluate_model(X, y)
# summarize performance
print('MSE: %.3f (%.3f)' % (mean(results), std(results)))