In [1]:
import numpy as np
import pandas as pd
import os

# Data Preprocessing

In [2]:
#reading 3 phase DPMU output from gridlabD
dpmu_phaseA = pd.read_csv('..\\..\\data\\summer\\targets\\trimmed_targets\\aug\\multi_voltageA.csv')
dpmu_phaseB = pd.read_csv('..\\..\\data\\summer\\targets\\trimmed_targets\\aug\\multi_voltageB.csv')
dpmu_phaseC = pd.read_csv('..\\..\\data\\summer\\targets\\trimmed_targets\\aug\\multi_voltageC.csv')

In [3]:
# dropping meter data
dpmu_phaseA = dpmu_phaseA.drop(['Meter1', 'Meter2', 'Meter3', 'Meter4', 'Meter5', '# timestamp'], axis=1)
dpmu_phaseB = dpmu_phaseB.drop(['Meter1', 'Meter2', 'Meter3', 'Meter4', 'Meter5', '# timestamp'], axis=1)
dpmu_phaseC = dpmu_phaseC.drop(['Meter1', 'Meter2', 'Meter3', 'Meter4', 'Meter5', '# timestamp'], axis=1)

In [4]:
phaseA = 0
phaseB = 1
phaseC = 2

In [5]:
# creating target dpmu dataframe
dpmu_data = pd.DataFrame()

In [6]:
for (columnName, columnData) in dpmu_phaseA.iteritems():
    split_column_names = columnName.split('_')
    house_name = 'house'+str(split_column_names[phaseA])
    dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
    dpmu_data[house_name] = dpmu_values

In [7]:
for (columnName, columnData) in dpmu_phaseB.iteritems():
    split_column_names = columnName.split('_')
    house_name = 'house'+str(split_column_names[phaseB])
    dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
    dpmu_data[house_name] = dpmu_values

In [8]:
for (columnName, columnData) in dpmu_phaseC.iteritems():
    split_column_names = columnName.split('_')
    house_name = 'house'+str(split_column_names[phaseC])
    dpmu_values = pd.Series(columnData.values).str.replace("i", "j").apply(lambda x: abs(complex(x)))
    dpmu_data[house_name] = dpmu_values

In [9]:
dpmu_data

,housenode1,housenode4,housenode7,housenode13,housenode10,housenode22,housenode19,housenode16,house2,house5,...,house20,house17,house3,house6,house9,house15,house12,house24,house21,house18
0,2363.994761,2376.991693,2375.718498,2352.767045,2361.400016,2361.418434,2361.399955,2355.548699,2406.953372,2404.984295,...,2418.908502,2419.060519,2366.926658,2366.504003,2366.229047,2337.377650,2347.430794,2344.827519,2347.430794,2342.868207
1,2369.150113,2380.564999,2378.824397,2364.411194,2371.481343,2371.381328,2371.481292,2368.629849,2405.459683,2405.474260,...,2418.010390,2417.574815,2368.194516,2368.069600,2367.731763,2340.824483,2350.315321,2347.744618,2350.315321,2346.217019
2,2365.298299,2377.165092,2375.486746,2355.295777,2366.150157,2365.965524,2366.150099,2362.358602,2394.717957,2405.675231,...,2422.115735,2422.440371,2368.214272,2367.751656,2367.378270,2337.614698,2347.366674,2344.726159,2347.366674,2343.008353
3,2363.462683,2374.634968,2372.936101,2347.306906,2360.276611,2360.103638,2360.276550,2355.788117,2394.474764,2405.163819,...,2423.836809,2424.406570,2368.147718,2367.509425,2367.188528,2337.128129,2346.915101,2344.249188,2346.915101,2342.826055
4,2361.685581,2374.155190,2372.415367,2348.156111,2360.364542,2360.259043,2360.364481,2356.159941,2391.559802,2404.115806,...,2421.638079,2422.127089,2370.321920,2369.072138,2368.743645,2340.504174,2350.219551,2347.680284,2350.219551,2346.162014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44635,2374.703288,2370.727952,2368.923606,2360.530336,2361.718523,2361.017211,2361.708488,2360.542782,2386.812050,2386.553896,...,2377.228365,2371.852837,2383.319090,2379.381705,2378.958603,2374.796995,2376.217110,2373.572793,2376.221997,2376.308574
44636,2379.981534,2375.998877,2374.364148,2369.098087,2370.206272,2370.419822,2370.206259,2369.105359,2378.721183,2378.590923,...,2361.129224,2354.212004,2385.851997,2382.892900,2382.408382,2381.193939,2382.110171,2379.197792,2382.110171,2382.637122
44637,2379.996042,2375.550753,2373.865940,2369.552048,2370.588511,2370.952665,2370.588497,2369.621640,2380.500618,2380.305073,...,2365.581802,2361.152771,2384.808413,2381.982941,2381.508342,2379.068204,2380.265189,2377.242809,2380.265189,2380.224830
44638,2383.999001,2381.842079,2381.343812,2374.606052,2375.602828,2375.908193,2375.602810,2374.706371,2383.074421,2383.878786,...,2374.826027,2371.336414,2380.764987,2377.501090,2377.154748,2371.196825,2372.551226,2369.488739,2372.551226,2372.230925
44639,2384.424349,2382.859673,2382.570365,2375.446792,2376.483367,2376.738342,2376.483349,2375.547547,2369.377868,2381.831902,...,2376.440558,2373.237563,2383.055426,2379.361139,2379.068573,2371.733831,2373.122160,2370.110261,2373.122160,2372.751463

In [10]:
# creating input grid dataframe
input_player_df = pd.DataFrame()

In [11]:
directory = os.getcwd()
directory = directory.replace('models\cnn', 'data\\all_data\\input-data\\scaled15_inputs')

In [12]:
for filename in os.listdir(directory):
    if str(filename).startswith('25.csv'):
        continue
    player = pd.read_csv(os.path.join(directory, filename))
    player['grid'] = player['grid'].str.replace("i", "j").apply(lambda x: complex(x))
    node_id = player['id'].loc[0]
    column_name_p = 'p_'+str(node_id)
    column_name_q = 'q_'+str(node_id)
    input_player_df[column_name_p] = player['grid'].apply(lambda x: x.real).head(1441)
    input_player_df[column_name_q] = player['grid'].apply(lambda x: x.imag).head(1441)

In [13]:
input_player_df

,p_1,q_1,p_10,q_10,p_11,q_11,p_12,q_12,p_13,q_13,...,p_5,q_5,p_6,q_6,p_7,q_7,p_8,q_8,p_9,q_9
0,27090.0,9747.148073,9855.0,4338.646565,31215.0,10417.369920,36660.0,14958.648518,16770.0,5558.826438,...,31245.0,12497.872264,12165.0,5477.719952,16365.0,7472.094154,15870.0,5259.694303,26400.0,11016.302870
1,27255.0,9646.606132,9840.0,3487.074552,30900.0,10974.292770,36495.0,14538.367031,16770.0,7350.408457,...,31260.0,12685.849079,4785.0,2251.992998,16770.0,5860.609411,9060.0,4174.105861,26370.0,10548.013653
2,27060.0,8985.897701,9840.0,4237.667133,31320.0,10607.140137,35565.0,13072.338506,16725.0,6354.680595,...,31035.0,13884.840991,3000.0,1349.749697,16395.0,6366.713911,9480.0,3890.114814,26280.0,10304.817429
3,26415.0,9447.594791,9840.0,4545.384961,30345.0,12419.509492,35085.0,16498.518817,16905.0,7498.696024,...,31215.0,11093.651281,3000.0,1061.044482,16365.0,7416.894623,9990.0,4039.188169,25095.0,11289.686596
4,25080.0,9613.187044,9960.0,3952.321958,26700.0,10713.127897,34995.0,13905.335980,16830.0,6796.907607,...,31095.0,10351.873228,3015.0,1393.199968,16335.0,7346.711269,9960.0,4653.769350,24825.0,10749.366178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1436,11490.0,5546.863003,17220.0,7264.852996,12345.0,5245.470323,17100.0,7682.535745,11190.0,5231.549594,...,56820.0,20870.341058,-43050.0,17514.908251,-4185.0,1702.792632,10275.0,4811.284929,-5715.0,1930.733911
1437,11490.0,5559.544467,20505.0,7157.422668,10845.0,4798.803455,16395.0,5762.307257,11175.0,4819.609444,...,56790.0,24983.121815,-46200.0,21966.061444,-5700.0,2495.774900,10305.0,4081.444887,-7470.0,2789.201986
1438,9780.0,3832.290128,39570.0,15202.578276,7995.0,3780.624575,15975.0,6059.983698,11160.0,4206.998331,...,56925.0,27325.833572,-40050.0,16041.177358,-10050.0,3766.129215,12060.0,4161.080795,-8925.0,4272.611058
1439,5745.0,2131.510387,49200.0,22332.405460,9825.0,4044.927978,19200.0,9218.762447,11160.0,4080.105657,...,56895.0,26641.338727,-20775.0,8811.719533,-13920.0,5786.614463,12570.0,5154.191443,-13065.0,5369.323535
1440,5745.0,2536.091513,45735.0,21000.453637,12120.0,5590.717185,22935.0,10899.425185,11160.0,4544.614278,...,56910.0,23136.357925,-11235.0,4670.274864,-5040.0,2403.395220,12525.0,4840.141048,-22785.0,9668.951036

# Neural Network

In [14]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_regression
from tensorflow import keras
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
#from tensorflow.keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras import layers
from keras.layers import Input, Embedding, LSTM, Dense
from keras.models import Model
from tensorflow.keras.constraints import non_neg

In [15]:
# get the dataset
def get_dataset():
    X, y = input_player_df.copy().to_numpy(), dpmu_data.copy().to_numpy()
    return X, y

In [16]:
# get the model
def get_model(n_inputs, n_outputs):
    #model = Sequential()
    #model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
    # Add a Dense layer
    #model.add(Dense(n_outputs))
    #model.compile(loss='mse', optimizer='adam')
    #model.summary()
    
    main_input = Input(shape=(n_inputs), name='main_input')
    x = Dense(1440, input_dim=n_inputs, activation='relu')(main_input)
    # supposed to be y = x*(weights) + main_input*(weights)+ b .. for each later
    x = Dense(720, input_dim=n_inputs, activation='relu', kernel_constraint=non_neg())(x)
    d = Dense(720, input_dim=n_inputs, activation='relu')(main_input)
    y = keras.layers.Add()([x, d])
    
    x = Dense(360, input_dim=n_inputs, activation='relu', kernel_constraint=non_neg())(y)
    d = Dense(360, input_dim=n_inputs, activation='relu')(main_input)
    y = keras.layers.Add()([x, d])
    
    x = Dense(180, input_dim=n_inputs, activation='relu', kernel_constraint=non_neg())(y)
    d = Dense(180, input_dim=n_inputs, activation='relu')(main_input)
    y = keras.layers.Add()([x, d])
    
    x = Dense(90, input_dim=n_inputs, activation='relu', kernel_constraint=non_neg())(y)
    d = Dense(90, input_dim=n_inputs, activation='relu')(main_input)
    y = keras.layers.Add()([x, d])
    
    # result gives you V-V0 for DPMU..... can we update y_test to reflect this...
    main_output = Dense(n_outputs, activation='relu', name='main_output')(y)
    model = Model(inputs=[main_input], outputs=[main_output])
    model.compile(loss='mse', optimizer='adam', metrics=[keras.metrics.MeanSquaredError()])
    #model.summary()
    return model

In [17]:
# evaluate a model using repeated k-fold cross-validation
def evaluate_model(X, y):
    results = list()
    n_inputs, n_outputs = X.shape[1], y.shape[1]
    # define evaluation procedure
    cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
    # enumerate folds
    for train_ix, test_ix in cv.split(X):
        # prepare data
        X_train, X_test = X[train_ix], X[test_ix]
        y_train, y_test = y[train_ix], y[test_ix]
        # define model
        model = get_model(n_inputs, n_outputs)
        # fit model
        model.fit(X_train, y_train, verbose=0, epochs=100)
        # evaluate model on test set
        mse = model.evaluate(X_test, y_test, verbose=0)
        # store result
        print(mse)
        results.append(mse)
    return results

In [ ]:
# load dataset
X, y = get_dataset()
# evaluate model
y_new = np.diff(y)
results = evaluate_model(X, y_new)
#y_pred = model.predict(X_test)
# summarize performance
print(results)
print('MSE/MAE: %.3f (%.3f)' % (mean(results), std(results)))
#y_new

[129.2122802734375, 129.2122802734375]
[134.25347900390625, 134.25347900390625]
[151.23760986328125, 151.23760986328125]
[4660.77734375, 4660.77734375]
[126.00575256347656, 126.00575256347656]
[548637.3125, 548637.3125]
[3734.7783203125, 3734.7783203125]
[2876.65771484375, 2876.65771484375]
[131.54017639160156, 131.54017639160156]
[134.63673400878906, 134.63673400878906]
[124.31700897216797, 124.31700897216797]
[118.61652374267578, 118.61652374267578]
[148.76080322265625, 148.76080322265625]
[150.77728271484375, 150.77728271484375]